### ISSUE TITLE
Transaction that exceeds idle_in_transaction_session_timeout produces NullPointerException

### ISSUE THREAD

**Issue by robotmrv** [eclipse-vertx/vertx-sql-client#1002]
### Version
vertx-pg-client: 4.1.1, 3.9.6
### Context
Transaction that exceeds idle_in_transaction_session_timeout produces NullPointerException  
```
java.lang.NullPointerException
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:246)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:131)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:111)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Do you have a reproducer?

```java
static Logger log = LoggerFactory.getLogger("testLogger");

private final io.vertx.pgclient.PgPool pgPool = ...;

Future<String> longTx() {
    return pgPool.getConnection().flatMap(conn -> conn.begin().flatMap(tx -> {
        return conn.query("set idle_in_transaction_session_timeout = 500").execute()
                .flatMap(rows -> {
                    log.info("after set idle_in_transaction_session_timeout");
                    Context ctx = Vertx.currentContext();
                    return Future.<String>future(promise -> {
                        ctx.owner().setTimer(3_000, event -> {
                            //make transaction longer than idle_in_transaction_session_timeout
                            log.info("timer");
                            tx.rollback(ar -> {
                                if (ar.succeeded()) {
                                    log.info("tx rollback success");
                                    promise.complete("OK");
                                } else {
                                    log.info("tx rollback error", ar.cause());
                                    promise.fail(ar.cause());
                                }
                            });
                        });
                    })
                    .eventually(unused -> conn.close());
                });
    }));
}
```

### Steps to reproduce

1. call longTx()
2. check logs for NullPointerException

**Comment by vietj** [comment]
thanks for the reproducer
