### ISSUE TITLE
An unclear `IllegalArgumentException` is thrown during the first query if creating a `PgPool` with a `Vertx` without `preferNativeTransport` set to true

### ISSUE THREAD

**Issue by ShreckYe** [eclipse-vertx/vertx-sql-client#1113]
#### Describe the feature

Code:
```java
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.pgclient.PgConnectOptions;
import io.vertx.pgclient.PgPool;
import io.vertx.sqlclient.PoolOptions;
import io.vertx.sqlclient.Tuple;

import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

public class PgPoolWithVertxWithUnixDomainSocketTest {
    public static void main(String[] args) {
        var vertx = Vertx.vertx(/*new VertxOptions().setPreferNativeTransport(true)*/);
        var pgPool = PgPool.pool(vertx,
                new PgConnectOptions()
                        .setHost("/var/run/postgresql")
                        .setDatabase("account_and_auth_test")
                        .setUser(System.getProperty("user.name")),
                new PoolOptions());

        pgPool.withTransaction(sqlConnection ->
                        sqlConnection.query("SELECT * FROM test;").execute())
                .onSuccess(rowSet -> System.out.println("Succeeded: " + StreamSupport.stream(rowSet.spliterator(), false).map(Tuple::deepToString).collect(Collectors.toList())))
                .onFailure(t -> {
                    System.out.println("Failed: " + t);
                    t.printStackTrace();
                })
                .flatMap(rowSet -> vertx.close());
    }
}

```

Output:
```text
Failed: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at io.vertx.core.net.impl.transport.Transport.channelFactory(Transport.java:183)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:96)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:90)
	at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:247)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:217)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:132)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:127)
	at io.vertx.pgclient.impl.PgConnectionFactory.doConnect(PgConnectionFactory.java:127)
	at io.vertx.pgclient.impl.PgConnectionFactory.doConnect(PgConnectionFactory.java:105)
	at io.vertx.pgclient.impl.PgConnectionFactory.doConnectInternal(PgConnectionFactory.java:82)
	at io.vertx.sqlclient.impl.ConnectionFactoryBase.doConnectWithRetry(ConnectionFactoryBase.java:101)
	at io.vertx.sqlclient.impl.ConnectionFactoryBase.lambda$connect$0(ConnectionFactoryBase.java:90)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.EventLoopContext.lambda$emit$1(EventLoopContext.java:57)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

By running the Java code above I get a very unclear `IllegalArgumentException`, whose stack trace doesn't involve any of my own code and is very difficult to debug. In addition, the code works if I don't pass a `Vertx` instance to `PgPool.pool`, so it becomes more confusing. Actually, It took me a lot of time to realize that it's caused by not adding `setPreferNativeTransport(true)`.

Therefore, I hope that a much clearer exception with an explanatory message is thrown in such a case when calling `PgPool.pool` with a `Vertx` with `preferNativeTransport` set to false, instead of an unclear and undebuggable one thrown during the first query.

#### Use cases

To help developers identify this mistake more quickly and save their time.

#### Contribution

I am not familiar with how Vert.x works under the hood. I hope the maintains can appoint someone to fix this simple issue, as it seems to me.

**Comment by vietj** [comment]
thanks we will add a more meaningfull error message in the transport class.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vert.x/commits/master

perhaps that we should also check that the passed vertx instance is capable of handling too.

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vertx-sql-client/issues/1114

**Comment by vietj** [comment]
Now the error will be caught earlier when creating the pool.
