### ISSUE TITLE
org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.

### ISSUE THREAD

**Issue by aomsweet** [eclipse-vertx/vertx-sql-client#1162]
### Version

vertx: 4.2.5
postgresql driver: 42.3.3

### Context

I use JdbcPool to execute a sql query with parameters and get this error `org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.`.

```java
    public Future<LocalDateTime> getCarrierLastUpdatedAt(SqlClient client, String carrier) {
        String sql = """
            SELECT updated_at FROM fare_history WHERE carrier = $1 ORDER BY updated_at DESC limit 1
            """;
        return client.preparedQuery(sql).execute(Tuple.of(carrier)).map(this::singleValue);
    }
```

console output:

```log
2022-03-14 16:58:34,585 ERROR [com.hai.ser.PriceTrendTransferService] (vert.x-eventloop-thread-0) : org.postgresql.util.PSQLException: The column index is out of range: 1, number of columns: 0.
	at org.postgresql.core.v3.SimpleParameterList.bind(SimpleParameterList.java:70)
	at org.postgresql.core.v3.SimpleParameterList.setStringParameter(SimpleParameterList.java:133)
	at org.postgresql.jdbc.PgPreparedStatement.bindString(PgPreparedStatement.java:1058)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:364)
	at org.postgresql.jdbc.PgPreparedStatement.setString(PgPreparedStatement.java:350)
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:950)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.setObject(PreparedStatementWrapper.java:289)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.fillStatement(JDBCPreparedQuery.java:134)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:72)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:219)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by vietj** [comment]
with JDBC you should use JDBC syntax that uses `?` instead of `$1`
