### ISSUE TITLE
Different error behavior between MsSql and Postgres when using streaming

### ISSUE THREAD

**Issue by ProgMaq** [eclipse-vertx/vertx-sql-client#1201]
### Questions

When I have forced an error, I get a different behavior between MsSql and Postgres when using streaming. Would it be interesting if the behavior were homogeneous?

### Version

4.3.1

### Context

If I use MsSQL I get an exception from the stream.exceptionHandler, the tx.exceptionHandler and finally the connection is closed. If I use postgres, it does not access any exceptionHandler or closeHandler, only the Future itself returns an error.

### Do you have a reproducer?

```
 final static Vertx vertx = Vertx.vertx();

  public static void main(String[] args) {
    vertx
      .exceptionHandler(t ->
        System.out.println("vertx.exceptionHandler called!")
      );

    test(getMsSqlPool())
      .onSuccess(v -> System.out.println("onSuccess"))
      .onFailure(t -> System.out.println("onFailure: " + t.getMessage()));
  }

  public static Future<Void> test(
    final Pool pool
  ) {
    return pool
      .withTransaction(tx -> tx
        .closeHandler(v -> System.out.println("tx.closeHandler called!"))
        //.exceptionHandler(t -> System.out.println("tx.exceptionHandler called!"))
        .prepare("SELECT invalid_function()")
        .compose(ps -> Future
          .future(promise -> ps
            .createStream(50)
            .exceptionHandler(t -> {
              System.out.println("stream.exceptionHandler");
              promise.tryFail(t);
            })
            .endHandler(v -> {
              System.out.println("stream.endHandler");
              promise.tryComplete();
            })
            .handler(row -> {
              System.out.println("stream.handler");
            })
          )
        )
      );
  }
```

### Return on MsSql

```
stream.exceptionHandler
tx.closeHandler called!
onFailure: Cannot invoke "java.lang.Number.intValue()" because "value" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Number.intValue()" because "value" is null
	at io.vertx.mssqlclient.impl.codec.ExtendedCursorQueryCommandCodec.handleReturnValue(ExtendedCursorQueryCommandCodec.java:138)
	at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:73)
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:65)
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.channelRead(TdsMessageDecoder.java:43)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Return on Postgres

`onFailure: ERROR: function invalid_function() does not exist (42883)`

### Steps to reproduce

1. Copy the code in any class
2. Create some credentials for postgres and another for sqlserver.
3. Run

### Extra

- openjdk 18.0.1.1 2022-04-22
- macos 12.4

**Comment by vietj** [comment]
MsSql seems to be a bug, cc @tsegismont

**Comment by tsegismont** [comment]
@ProgMaq there is fix coming for the NPE in #1202 

With the proposed changes, you will get an `MSSQLException` with a proper message in the `exceptionHandler` of the stream.
However, you cannot get the same behavior as with Postgres, because with MSSQL we can only get feedback at a later stage (when executing `cursorprepexec`)

**Comment by ProgMaq** [comment]
@[tsegismont](https://github.com/tsegismont) Thanks for the speed of the fix and for this good explanation:

> However, you cannot get the same behavior as with Postgres, because with MSSQL we can only get feedback at a later stage (when executing cursorprepexec)

**Comment by vietj** [comment]
thanks @tsegismont and @ProgMaq
