### ISSUE TITLE
Oracle : java.sql.SQLFeatureNotSupportedException: Fonction non prise en charge: setCursorName

### ISSUE THREAD

**Issue by larousso** [eclipse-vertx/vertx-sql-client#1213]
### Version

4.3.2

### Context

Using cursor with oracle vertx client.

I have the following dependencies : 

```
def oracleVersion               = "21.6.0.0"
implementation "com.oracle.database.jdbc:ojdbc11:$oracleVersion"
implementation "com.oracle.database.nls:orai18n:$oracleVersion"
```

The code that use is : 

```java 

    public static <T> Source<T, NotUsed> stream(SqlConnection sqlConnexion, int size, String query, Tuple args, Function<Row, T> convert) {
        AtomicBoolean first = new AtomicBoolean(true);
        return Source.unfoldResourceAsync(
                () -> sqlConnexion.prepare(query).map(q -> Objects.isNull(args) ? q.cursor() : q.cursor(args)).toCompletionStage(),
                cursor -> {
                    if (first.getAndSet(false) || cursor.hasMore()) {
                        return cursor.read(size).map(rs ->
                                Optional.of(List.ofAll(rs)
                                        .map(convert))
                        ).toCompletionStage();
                    } else {
                        return CompletableFuture.completedFuture(Optional.empty());
                    }
                },
                cursor -> cursor.close().map(Done.getInstance()).toCompletionStage()
        ).mapConcat(l -> l);
    }
```

This exception is thrown : 

```

java.sql.SQLFeatureNotSupportedException: Fonction non prise en charge: setCursorName
	at oracle.jdbc.driver.OracleStatement.setCursorName(OracleStatement.java:3905) ~[ojdbc11-21.6.0.0.jar:21.6.0.0.0]
		at oracle.jdbc.driver.OracleStatement.setCursorName(OracleStatement.java:3905) ~[ojdbc11-21.6.0.0.jar:21.6.0.0.0]
		at oracle.jdbc.driver.OracleStatementWrapper.setCursorName(OracleStatementWrapper.java:322) ~[ojdbc11-21.6.0.0.jar:21.6.0.0.0]
		at io.vertx.oracleclient.impl.commands.OracleCursorQueryCommand.applyStatementOptions(OracleCursorQueryCommand.java:53) ~[vertx-oracle-client-4.3.2.jar:4.3.2]
		at io.vertx.oracleclient.impl.commands.QueryCommand.lambda$prepare$2(QueryCommand.java:110) ~[vertx-oracle-client-4.3.2.jar:4.3.2]
		at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[vertx-core-4.3.2.jar:4.3.2]
		at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.3.2.jar:4.3.2]
		at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[vertx-core-4.3.2.jar:4.3.2]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
		at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]


```

**Comment by tsegismont** [comment]
Hi @larousso , thanks for reporting this. This should be resolved in the next release https://github.com/eclipse-vertx/vertx-sql-client/issues/1185

**Comment by tsegismont** [comment]
Already tracked in #1185
