### ISSUE TITLE
MSSQLCommandCodec Unsupported Token 0x2c when streaming

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-sql-client#1220]
Reported on the user group

> MSSQL server version: 15.0.2095.3
> Prepared statement: "EXEC [quick].[brown_fox]"
> Exception:
> For this command -> ExtendedCursorQueryCommandCodec
> java.lang.UnsupportedOperationException: Unsupported token: 0x2c
>     at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:82)
>     at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:65)
>

**Comment by tsegismont** [comment]
> Updated with more test results:
> 
> I am running the following:
> CODE
> sqlConnection.prepare("EXEC test.GetTest", event -> {
> if (event.succeeded()) {
> PreparedStatement ps = event.result();
> RowStream<Row> stream = ps.createStream(20);
> stream.exceptionHandler(handler -> log.error("stream exception handler:{}", handler));
> stream.endHandler(v -> {
> 
> log.info("End of stream. {}" , counter);
> });
> stream.handler(row -> {
> counter++;
> // [log.info](http://log.info/)("streaming row:{}", toJson(row));
> });
> }
> 
> the 'test.GetTest' SP is
> 
> CREATE PROCEDURE test.GetTest
> 
> AS 
> 
> BEGIN
> 
>    SELECT * 
> 
>    FROM [my].[test]
> 
> END
> 
> Using vertx-sql-client.4.3.1 + vertx-mssql-client-4.2.7
> No errors. 
> 
> Using vertx-sql-client.4.3.1 + vertx-mssql-client-4.3.1
> java.lang.IndexOutOfBoundsException: index: 35, length: 3600 (expected: range(0, 3598))
>     at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
>     at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
>     at io.netty.buffer.AbstractUnpooledSlicedByteBuf.getCharSequence(AbstractUnpooledSlicedByteBuf.java:263)
>     at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:518)
>     at io.vertx.mssqlclient.impl.codec.DataType$31.decodeValue(DataType.java:838)
>     at io.vertx.mssqlclient.impl.codec.DataType$28.decodeValue(DataType.java:773)
>     at io.vertx.mssqlclient.impl.codec.RowResultDecoder.decodeMssqlNbcRow(RowResultDecoder.java:96)
>     at io.vertx.mssqlclient.impl.codec.RowResultDecoder.handleNbcRow(RowResultDecoder.java:54)
>     at io.vertx.mssqlclient.impl.codec.QueryCommandBaseCodec.handleNbcRow(QueryCommandBaseCodec.java:46)
>     at io.vertx.mssqlclient.impl.codec.ExtendedCursorQueryCommandCodec.handleNbcRow(ExtendedCursorQueryCommandCodec.java:155)
>     at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:56)
>     at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:65)
>     at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.channelRead(TdsMessageDecoder.java:43)
>     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
>     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>     at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
>     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
>     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
>     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
>     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
>     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
>     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
>     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>     at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by tsegismont** [comment]
More info

> I have found the reason for this failure.
> 
> If I use any of the SET, IF, IF..ELSE in the SP of MSSQL, i will encounter the problem.
> 
> MSSQL server version: 15.0.2095.3
> mssql-client 4.3.1, 
> 
>     Normal queries will drop the response with NO errors. returning 0 results
>     Result streaming queries will throw an Unsupported Token exception.
> 
> I traced the network packets received in Netty for the results of a normal query.
> The following is the first few bytes of the packet received (highlighted in RED is the difference)
> PROBLEMATIC PACKET: 04 01 01 30 01 3a 01 00 ff 01 00 c0 00 00 00 00 00 00 00 00 00 81 08 00 00 00 00 00 01 00 26 08 02 69 00 64 00 
> WORKING PACKET.        :  04 01 01 23 01 3a 01 00 81 08 00 00 00 00 00 01 00 26 08 02 69 00 64 00
