### ISSUE TITLE
vertx-pg-client not compatible with PostgreSQL 14+

### ISSUE THREAD

**Issue by jpnovais** [eclipse-vertx/vertx-sql-client#1249]
### Version

Which version(s) did you encounter this bug ?
- `io.vertx:vertx-stack:4.3.4`
- `io.vertx:vertx-pg-client:4.3.4`

### Context
vertx-pg-client not compatible with PostgreSQL 14 and 15;

Stack trace error
```
java.lang.NoClassDefFoundError: com/ongres/scram/common/stringprep/StringPreparation
	at io.vertx.pgclient.impl.codec.InitCommandCodec.handleAuthenticationSasl(InitCommandCodec.java:60)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeAuthentication(PgDecoder.java:366)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:140)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:112)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
         ...
Caused by: java.lang.ClassNotFoundException: com.ongres.scram.common.stringprep.StringPreparation
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
```

### Do you have a reproducer

* [reproducer porject](https://github.com/jpnovais/vertx-pg-sql-client-pg15-bug-reproducer)

### Steps to reproduce

1. Start container with PostgreSQL 14  
```
docker compose up postgres
```

2. Run application
```
./gradlew run
```

### Extra

* vertx version: 4.3.4 (latest atm)
* Os Version: MacOs 12.6 Monterey on M1
* Docker version 20.10.17, build 100c701
* java --version
```
java 17.0.3 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)
```

**Comment by vietj** [comment]
you need to add 

```java
    <dependency>
      <groupId>com.ongres.scram</groupId>
      <artifactId>client</artifactId>
      <version>2.1</version>
      <optional>true</optional>
    </dependency>
```

to your dependencies
