### ISSUE TITLE
ExtendedQueryCommand.params NoSuchMethodError

### ISSUE THREAD

**Issue by alxxyz** [eclipse-vertx/vertx-sql-client#1278]
We are receiving 
```
java.lang.NoSuchMethodError: 'io.vertx.sqlclient.impl.TupleInternal io.vertx.sqlclient.impl.command.ExtendedQueryCommand.params()'
	at io.vertx.mssqlclient.impl.codec.ExtendedQueryCommandCodec.prepexecRequestParams(ExtendedQueryCommandCodec.java:25)
	at io.vertx.mssqlclient.impl.codec.ExtendedQueryCommandBaseCodec.sendPrepexecRequest(ExtendedQueryCommandBaseCodec.java:90)

```
for the 
```
return sessionFactory.withSession(session -> {
            return session.createQuery("from ProductEntity p", ProductEntity.class)
                    .getResultList();
        }).convert().with(toMono());
```
and dependencies
```
<dependency>
            <groupId>org.hibernate.reactive</groupId>
            <artifactId>hibernate-reactive-core</artifactId>
            <version>1.1.9.Final</version>
        </dependency>
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>mutiny-reactor</artifactId>
            <version>1.7.0</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-mssql-client</artifactId>
            <version>4.3.8</version>
        </dependency>
```

**Comment by alxxyz** [comment]
The issue was that `hibernate-reactive-core` use `vertx-sql-client` version `4.3.4`, but we use `vertx-mssql-client` version `4.3.8`

**Comment by tsegismont** [comment]
Thanks for letting us know
