### ISSUE TITLE
[MSSQL] Unable to decode typeInfo for SSVARIANT

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1312]
A simple select on the information schema:
```
 select * from INFORMATION_SCHEMA.SEQUENCES
```

Causes the following exception:
```
Caused by: java.lang.UnsupportedOperationException: Unable to decode typeInfo for SSVARIANT
	at io.vertx.mssqlclient.impl.codec.DataType.decodeTypeInfo(DataType.java:1042) ~[vertx-mssql-client-4.4.1.jar:4.4.1]
	at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.handleColumnMetadata(MSSQLCommandCodec.java:120) ~[vertx-mssql-client-4.4.1.jar:4.4.1]
	at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:51) ~[vertx-mssql-client-4.4.1.jar:4.4.1]
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:65) ~[vertx-mssql-client-4.4.1.jar:4.4.1]
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.channelRead(TdsMessageDecoder.java:43) ~[vertx-mssql-client-4.4.1.jar:4.4.1]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.90.Final.jar:4.1.90.Final]
```

This is the only element we create in the database (although, it doesn't seem to matter):
```
create table BASIC_TYPES_TABLE (unmapped_column int)
```

Tested with MSSQL 2022-latest and Vert.x 4.3.8 and 4.4.1

**Comment by DavideD** [comment]
@tsegismont ^
