### ISSUE TITLE
DB client result in java.lang.IllegalStateException: Expected code point 14ac but was fffffffe rows 

### ISSUE THREAD

**Issue by argenstijn** [eclipse-vertx/vertx-sql-client#1351]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

4.4.5

### Context

Using Vert.x 4.4.5 and 4.4.4 (used in quarkus) result in the following error while connecting to a DB2 database (SQL110580).:

java.lang.IllegalStateException: Expected code point 14ac but was fffffffe rows 

I am using Java 17 and maven 3.9.4

See also [quarkus issue/vertx client](https://github.com/quarkusio/quarkus/issues/14117)

### Do you have a reproducer?

No

### Steps to reproduce

1. ...
2. ...
3. ...
4. ...

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by argenstijn** [comment]
java.lang.IllegalStateException: Expected code point 14ac but was fffffffe
	at io.vertx.db2client.impl.drda.DRDAResponse.parseLengthAndMatchCodePoint(DRDAResponse.java:1135)
	at io.vertx.db2client.impl.drda.DRDAConnectResponse.parseACCSECRD(DRDAConnectResponse.java:1401)
	at io.vertx.db2client.impl.drda.DRDAConnectResponse.parseACCSECreply(DRDAConnectResponse.java:1176)
	at io.vertx.db2client.impl.drda.DRDAConnectResponse.readAccessSecurity(DRDAConnectResponse.java:35)
	at io.vertx.db2client.impl.codec.InitialHandshakeCommandCodec.decodePayload(InitialHandshakeCommandCodec.java:101)
	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:79)
	at io.vertx.db2client.impl.codec.DB2Decoder.decode(DB2Decoder.java:52)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
