### ISSUE TITLE
Unsupported type java.math.BigDecimal

### ISSUE THREAD

**Issue by zclcs** [eclipse-vertx/vertx-sql-client#1473]
### Version
vert.x 4.5.10
mysql 8.0

`java.lang.UnsupportedOperationException: Unsupported type java.math.BigDecimal
	at io.vertx.mysqlclient.impl.MySQLRowImpl.get(MySQLRowImpl.java:90)
	at com.enterprise.help.platform.dao.vo.TestVoRowMapper.map(TestVoRowMapper.java:38)
	at com.enterprise.help.platform.dao.vo.TestVoRowMapper.map(TestVoRowMapper.java:7)
	at io.vertx.sqlclient.impl.RowSetImpl.lambda$collector$2(RowSetImpl.java:42)
	at io.vertx.sqlclient.impl.RowDecoder.handleRow(RowDecoder.java:69)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.handleRows(QueryCommandBaseCodec.java:127)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:66)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:108)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePackets(MySQLDecoder.java:69)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.channelRead(MySQLDecoder.java:45)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:455)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at `java.base/java.lang.Thread.run(Thread.java:840)

![image](https://github.com/user-attachments/assets/180a396c-a273-4ed1-84fb-3fb9f829f7e7)

It seems that row.get(java.math.BigDecimal.class, idx) should be row.getBigDecimal(idx)

**Comment by tsegismont** [comment]
To clarify, what you found is that `getBigDecimal(idx)` works, but not `get(BigDecimal.class,idx)`?

**Comment by zclcs** [comment]
> To clarify, what you found is that `getBigDecimal(idx)` works, but not `get(BigDecimal.class,idx)`?

yes

**Comment by tsegismont** [comment]
Fixed by b410327a

**Comment by alexpoletaev** [comment]
> Fixed by [b410327](https://github.com/eclipse-vertx/vertx-sql-client/commit/b410327a2627d8f5736603ceb75ec6742dc47655)

Hi, it seems there is the same issue with the postrges driver as well. I'm getting such exception: `java.lang.UnsupportedOperationException: Unsupported type java.math.BigDecimal`. Vertx version 4.5.14

**Comment by tsegismont** [comment]
@alexpoletaev for Pg client, use the Numeric type: https://vertx.io/docs/vertx-pg-client/java/#_handling_numeric

**Comment by alexpoletaev** [comment]
@tsegismont , but what if I need to use BigDecimal type exactly or just don't want to use vertx specific types? Why we can't do the same fix for the postgres implementation as well?
Consider such a class:
```java
@DataObject
@RowMapped(formatter = SnakeCase.class)
@ParametersMapped
@JsonGen
public class SomeBean {

    public SomeBean() {
    }

    public SomeBean(JsonObject jsonObject) {
        SomeBeanConverter.fromJson(jsonObject, this);
    }

    public JsonObject toJson() {
        JsonObject json = new JsonObject();
        SomeBeanConverter.toJson(this, json);
        return json;
    }

    private BigDecimal amount;

    //getters and setters
}
```
and the row mapper will generate such conversion:
```java
// omit all other data
if ((idx = row.getColumnIndex("amount")) != -1 && (val = row.get(java.math.BigDecimal.class, idx)) != null) {
  obj.setAmount((java.math.BigDecimal)val);
}
```
so we can expect that conversion should just work, considering that the client core implementation already has all necessary methods.

Please check my pull request https://github.com/eclipse-vertx/vertx-sql-client/pull/1509
