### ISSUE TITLE
[MSSQL] Add support for XML data type

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#1475]
[Based on the documentation](https://vertx.io/docs/vertx-mssql-client/java/#_data_types_supported),  [the `xml` data type](https://learn.microsoft.com/en-us/sql/relational-databases/xml/xml-data-type-and-columns-sql-server?view=sql-server-ver16) is not supported in MSSQL.
Example of column definition:
```sql
xmlColumn xml
```

It currently throws (during a select sql query):
```
Caused by: java.lang.UnsupportedOperationException: Unable to decode typeInfo for XML
	at io.vertx.mssqlclient.impl.codec.DataType.decodeTypeInfo(DataType.java:1065)
	at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.handleColumnMetadata(MSSQLCommandCodec.java:120)
	at io.vertx.mssqlclient.impl.codec.MSSQLCommandCodec.decode(MSSQLCommandCodec.java:51)
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.decodeMessage(TdsMessageDecoder.java:75)
	at io.vertx.mssqlclient.impl.codec.TdsMessageDecoder.channelRead(TdsMessageDecoder.java:47)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	... 20 more
```

**Comment by tsegismont** [comment]
Thanks @DavideD . If we want to support this, we need to decided which Java type can represent XML. Perhaps we need a custom type in Vert.x SQL Clients.
