### ISSUE TITLE
NullPointerException on connection when PgPoolOptions.user is null

### ISSUE THREAD

**Issue by Firgeis** [eclipse-vertx/vertx-sql-client#255]
Exception should be catch or a validation should be performed

Below is the full stack trace:

java.lang.NullPointerException
	at io.netty.buffer.ByteBufUtil.utf8MaxBytes(ByteBufUtil.java:582)
	at io.netty.buffer.AbstractByteBuf.setCharSequence0(AbstractByteBuf.java:696)
	at io.netty.buffer.AbstractByteBuf.writeCharSequence(AbstractByteBuf.java:1183)
	at io.reactiverse.pgclient.impl.codec.util.Util.writeCStringUTF8(Util.java:60)
	at io.reactiverse.pgclient.impl.codec.encoder.MessageEncoder.writeStartupMessage(MessageEncoder.java:128)
	at io.reactiverse.pgclient.impl.InitCommand.exec(InitCommand.java:59)
	at io.reactiverse.pgclient.impl.SocketConnection.checkPending(SocketConnection.java:249)
	at io.reactiverse.pgclient.impl.SocketConnection.schedule(SocketConnection.java:227)
	at io.reactiverse.pgclient.impl.SocketConnection.sendStartupMessage(SocketConnection.java:119)
	at io.reactiverse.pgclient.impl.PgConnectionFactory.lambda$create$0(PgConnectionFactory.java:97)
	at io.reactiverse.pgclient.impl.PgConnectionFactory.lambda$doConnect$4(PgConnectionFactory.java:171)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:125)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:86)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:151)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:18)
	at io.vertx.core.net.impl.NetClientImpl.lambda$null$7(NetClientImpl.java:222)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180)
	at io.vertx.core.net.impl.NetClientImpl.lambda$connected$8(NetClientImpl.java:217)
	at io.vertx.core.net.impl.VertxHandler.setConnection(VertxHandler.java:87)
	at io.vertx.core.net.impl.VertxHandler.handlerAdded(VertxHandler.java:104)

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by Firgeis** [comment]
This is running on a suspend function in a Coroutine Verticle. I think that providing the full code would be too cumbersome.
`    
val options = PgPoolOptions()
options.host = "valid url"
options.database = "valid database"
options.user = null
options.password = "some password"

val client = PgClient.pool(vertx, options)
val sql = "valid SQL"
client.queryAwait(sql)
`

**Comment by vietj** [comment]
can you provide a reproducer project which would make super easy to debug ?

**Comment by Firgeis** [comment]
Here you go.

[VertxStarter.zip](https://github.com/reactiverse/reactive-pg-client/files/3035806/VertxStarter.zip)

**Comment by BillyYccc** [comment]
Maybe we should add `Objects.requireNonNull()` check for setting parameters in `PgConnectOptions`.

**Comment by BillyYccc** [comment]
Closed as this has been resolved by adding null checks for those options.
