### ISSUE TITLE
NullPointerException when PostgreSQL is down after connecting

### ISSUE THREAD

**Issue by renannprado** [eclipse-vertx/vertx-sql-client#273]
I don't know how to reproduce 100% of the cases.
But I'm trying vertx and this postgresql driver and what I'm trying to see is the behavior of the application when it's running but for some reason loses connection to PostgreSQL.

After the application is up and running, I kill my local PostgreSQL that is running inside of docker and in some situations I get a NullPointerException coming from inside of the `reactive-pg-client` lib.

This is the code:

```kotlin
suspend fun main(args: Array<String>) {
    val vertx = Vertx.vertx()

    // Pool options
    var options = pgPoolOptionsOf(
            port = 5432,
            host = "localhost",
            database = "client_data_management",
            user = "client-service",
            password = "client-service",
            connectTimeout = 5,
            reconnectInterval = 5,
            reconnectAttempts = 10,
            maxSize = 5)

    try {
        val pgConnection = PgClient.connectAwait(vertx, options)

        val clientEntityRepository = ClientEntityRepositoryPostgreSQL(pgConnection)

        val router = Router.router(vertx)

        router.get("/").handler { httpRequest ->
            GlobalScope.launch(vertx.dispatcher()) {
                clientEntityRepository.findAll().forEach {
                    httpRequest.response().end(it.toString())
                }
            }
        }.failureHandler {
            it.failure().printStackTrace()
            it.response().end("error")
        }

        vertx.createHttpServer()
                .requestHandler(router::accept)
                .listenAwait(8080)

    } catch (e: Exception) {
        println("exception")
        vertx.close()
    }
}
```

```
java.lang.NullPointerException
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeError(MessageDecoder.java:253)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeMessage(MessageDecoder.java:142)
	at io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:122)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "vert.x-eventloop-thread-0" io.vertx.core.VertxException: Connection not open CLOSED
	at io.reactiverse.pgclient.impl.SocketConnection.schedule(SocketConnection.java:229)
	at io.reactiverse.pgclient.impl.PgConnectionImpl.schedule(PgConnectionImpl.java:67)
	at io.reactiverse.pgclient.impl.PgConnectionImpl.schedule(PgConnectionImpl.java:59)
	at io.reactiverse.pgclient.impl.PgClientBase.query(PgClientBase.java:48)
	at io.reactiverse.pgclient.impl.PgClientBase.query(PgClientBase.java:38)
	at io.reactiverse.pgclient.impl.PgConnectionImpl.query(PgConnectionImpl.java:26)
	at xxx.ClientEntityRepositoryPostgreSQL$findAll$result$1.invoke(ClientRepository.kt:28)
	at xxx.ClientEntityRepositoryPostgreSQL$findAll$result$1.invoke(ClientRepository.kt:11)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt.awaitEvent(VertxCoroutine.kt:66)
	at io.vertx.kotlin.coroutines.VertxCoroutineKt.awaitResult(VertxCoroutine.kt:96)
	at xxx.ClientEntityRepositoryPostgreSQL.findAll(ClientRepository.kt:28)
	at xxx.AppKt$main$2$1.invokeSuspend(App.kt:42)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:230)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:64)
	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:413)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at xxx.AppKt$main$2.handle(App.kt:40)
	at xxx.AppKt$main$2.handle(App.kt)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:227)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:121)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:134)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:80)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:41)
	at io.vertx.ext.web.Router.accept(Router.java:64)
	at xxx.AppKt$main$4.invoke(App.kt:57)
	at xxx.AppKt$main$4.invoke(App.kt)
	at xxx.AppKt$sam$io_vertx_core_Handler$0.handle(App.kt)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleBegin(HttpServerRequestImpl.java:150)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:129)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:390)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by mkulak** [comment]
I'm seeing the same issue. Our postgres is restarted 1-2 times per week while app is running. Most of the time PgPool is able to reconnect. But sometimes NPE happens and then pool is dead - application just hangs. Restarting app helps.
> [vert.x-eventloop-thread-0] - [PgConnection exceptionHandler:] - [ java.lang.NullPointerException|\tat io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeError(MessageDecoder.java:253)|\tat io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.decodeMessage(MessageDecoder.java:142)|\tat io.reactiverse.pgclient.impl.codec.decoder.MessageDecoder.channelRead(MessageDecoder.java:122)|\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)|\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)|\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)|\tat io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)|\tat io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)|\tat io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)|\tat io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)|\tat io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)|\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)|\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)|\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)|\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)|\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)|\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)|\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)|\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)|\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)|\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)|\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)|\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)|\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)|\tat io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)|\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)|\tat java.lang.Thread.run(Thread.java:748)]

**Comment by vietj** [comment]
can you try with the current vertx sql client snapshots and report the error if any ?

**Comment by vietj** [comment]
we need in this project to reimplement the PgPool using the existing pool from vertx-core

**Comment by mkulak** [comment]
Unfortunately I can't try snapshots now. 
We can reproduce problem with hanging by doing full vacuum on postgres db (after some inserts/deletes). For our use case full vacuum takes ~10 minutes to complete. During that time db doesn't not respond (as expected) but afterwards connection pool doesn't recover - it stay unresponsive. Every call to db basically hangs forever.

**Comment by Globegitter** [comment]
I am using v3.8.1 in combination with https://github.com/zonkyio/embedded-postgres for unit testing and when closing the database down after all the tests have run I am seeing a NullPointerException. Not a problem as I am now closing the pool beforehand but it did come quite unexpected and took me quite some time to figure out.

I also tested 4.0.0-milestone2 and seeing the same behaviour.

**Comment by vietj** [comment]
do you have a reproducer @Globegitter ?

**Comment by Globegitter** [comment]
Will set something up.

**Comment by vietj** [comment]
thank you

**Comment by tsegismont** [comment]
Closing as outdated
