### ISSUE TITLE
String encoding in windows

### ISSUE THREAD

**Issue by cjsworld** [eclipse-vertx/vertx-sql-client#449]
Insert string value with PreparedQuery, works fine with linux/mac, but error in windows.
log:
```
io.vertx.mysqlclient.MySQLException: Incorrect string value: '\xA1\xBEAppl...' for column 'content' at row 1
	at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:130)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:37)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:55)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:95)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePayload(MySQLDecoder.java:62)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:51)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Unknown Source)
```

MySQL config:
```
character_set_client	utf8mb4
character_set_connection	utf8mb4
character_set_database	utf8mb4
character_set_filesystem	binary
character_set_results	
character_set_server	utf8mb4
character_set_system	utf8
character_sets_dir	C:\Program Files\MySQL\MySQL Server 8.0\share\charsets\
```

The `\xA1\xBE` is `【` in gbk, witch is the default encoding in my windows. 

The string value is encoded in
```
package io.vertx.mysqlclient.impl.codec;

class DataTypeCodec {

    static void encodeBinary(DataType dataType, Object value, ByteBuf buffer) {
        //...
        case STRING:
        case VARSTRING:
        default:
            binaryEncodeText(String.valueOf(value), buffer);
        //...
    }
    
    private static void binaryEncodeText(String value, ByteBuf buffer) {
        BufferUtils.writeLengthEncodedString(buffer, value);
    }
}
```
```
package io.vertx.mysqlclient.impl.util;
class BufferUtils {
  public static void writeLengthEncodedString(ByteBuf buffer, String value, Charset charset) {
    byte[] bytes = value.getBytes(charset);
    writeLengthEncodedInteger(buffer, bytes.length);
    buffer.writeBytes(bytes);
  }

  public static void writeLengthEncodedString(ByteBuf buffer, String value) { //<---This is used
    byte[] bytes = value.getBytes();
    writeLengthEncodedInteger(buffer, bytes.length);
    buffer.writeBytes(bytes);
  }
}
```
That is, buffer will be filled with string's bytes with system's default charset.
Should it be UTF-8? Since default charset in MYSQL is utf8 or utf8-mb4, even in windows version of MYSQL. Or read server's config will be better.

Change jvm's default encoding by adding `-Dfile.encoding=utf-8` parameter will solve the problem, but the console output will be a mess.

**Comment by BillyYccc** [comment]
We have recognized this and a PR is in progress for this, see #448

cjsworld <notifications@github.com> 于 2019年11月20日周三 11:30写道：

**Comment by BillyYccc** [comment]
duplicated as https://github.com/eclipse-vertx/vertx-sql-client/issues/447
