### ISSUE TITLE
Client is Closed

### ISSUE THREAD

**Issue by ocio28** [eclipse-vertx/vertx-sql-client#457]
i using io.vertx:vertx-pg-client:3.8.3 and I don't know how to reproduce, it's very erratic can goes days without a problem.

Thanks!!

`java.lang.IllegalStateException: Client is closed
	at io.vertx.core.net.impl.NetClientImpl.checkClosed(NetClientImpl.java:147) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:173) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:168) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:157) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.pgclient.impl.PgConnectionFactory.doConnect(PgConnectionFactory.java:191) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.pgclient.impl.PgConnectionFactory.connect(PgConnectionFactory.java:118) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.pgclient.impl.PgConnectionFactory.connectAndInit(PgConnectionFactory.java:104) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.pgclient.impl.PgPoolImpl.connect(PgPoolImpl.java:47) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.sqlclient.impl.ConnectionPool.check(ConnectionPool.java:201) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.sqlclient.impl.ConnectionPool.access$500(ConnectionPool.java:34) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.sqlclient.impl.ConnectionPool$PooledConnection.handleClosed(ConnectionPool.java:147) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleClose(SocketConnectionBase.java:257) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleClosed(SocketConnectionBase.java:229) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.ConnectionBase.handleClosed(ConnectionBase.java:317) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.NetSocketImpl.handleClosed(NetSocketImpl.java:357) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.VertxHandler.lambda$channelInactive$4(VertxHandler.java:162) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:162) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:420) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:223) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.vertx.pgclient.impl.codec.PgCodec.channelInactive(PgCodec.java:57) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1417) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:913) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[jengibre-backoffice-0.1.7-fat.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]`

**Comment by BillyYccc** [comment]
Can you give a description on what the problem is and how that happens?

**Comment by ocio28** [comment]
hi, i think it was my bad, i fix a connection.close() that i missing and the error didn't happen again (so far)

close de issue and if happening again i report it with more info

Thanks!!

**Comment by BillyYccc** [comment]
Thanks for letting us know
