### ISSUE TITLE
3.8.4 | vertx-pg-client | io.vertx.core.VertxException: closed

### ISSUE THREAD

**Issue by estet90** [eclipse-vertx/vertx-sql-client#481]
I have a floating bug
configuration:
```
var config = new PgConnectOptions()
                .setDatabase(properties.getProperty("PGDBNAME"))
                .setHost(properties.getProperty("PGHOST"))
                .setPort(Integer.parseInt(properties.getProperty("PGPORT")))
                .setReconnectAttempts(1)
                .setReconnectInterval(10)
                .setProperties(conProps)
                .setIdleTimeout(10);
var poolConfig = new PoolOptions()
                .setMaxSize(20);
return PgPool.pool(config, poolConfig);
```
Error occurs after 10 seconds (IdleTimeout), but in the db logs I do not see such long queries
trace:
```
Caused by: io.vertx.core.VertxException: closed
	at io.vertx.pgclient.impl.codec.PgCodec.channelInactive(PgCodec.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1417)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:913)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vietj** [comment]
this `setIdleTimeout(10` is for inactive connections, not for queries

**Comment by estet90** [comment]
> this `setIdleTimeout(10` is for inactive connections, not for queries

How I can solve my problem?

**Comment by vietj** [comment]
the proper way is that you should set a timeout yourself and cancel the current query using the PG specific feature using https://vertx.io/docs/vertx-pg-client/java/#_cancelling_request

**Comment by vietj** [comment]
we could have a specific timeout for PG that does it for you on a connection perhaps, I don't know how much efficient this is, given that cancelling a query opens a connection

**Comment by estet90** [comment]
The essence of the problem is that I could not get the result of the request, and the connection was closed. This happens infrequently, but I want to exclude such an error.

**Comment by BillyYccc** [comment]
I think a better way to handle this is that we could add a command timeout
for each connection, when the query exceeds timeout we can let the query
handler fail–fast.

Julien Viet <notifications@github.com> 于 2020年1月9日周四 17:51写道：

**Comment by estet90** [comment]
> Error occurs after 10 seconds (IdleTimeout), but in the db logs I do not see such long queries
1. There isn't any result in my program, but
2. Query in db was completed

**Comment by vietj** [comment]
it might be a bug ? do you have a reproducer ?

**Comment by vietj** [comment]
no it's not a bug if you set TCP idle timeout then it will be closed, we are eventually discussing a feature that would set a timer and cancel a query using PG query cancellation mechanism

**Comment by vietj** [comment]
ah for bug I mean that you might be having a bug where the client is not performing the query at all

**Comment by estet90** [comment]
> ah for bug I mean that you might be having a bug where the client is not performing the query at all
yes, most likely it is
