### ISSUE TITLE
No exception thrown when connection being reset

### ISSUE THREAD

**Issue by dangfan** [eclipse-vertx/vertx-sql-client#552]
### Questions

I'm connecting to a MySQL server that closes idle connections quite often. After the connection is closed, querying will fail but no exception is thrown (I'm using Kotlin coroutine).
The results differ when directly use the MySQLPool to query or use the Connection to query.
When I use the MySQLPool to query, it simply "stucks" and nothing happens. However, when using the Connection, I can get these lines printed on my console:

```
java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
I'm sure that this stack trace is not from my code.

### Version

3.8.5

### Do you have a reproducer?

To reproduce this issue is not easy. The key idea is to simulate the disconnect operation. Here are the steps to reproduce:

1. Install MySQL on another machine.
2. Do some queries and do not close the client.
3. Use iptables (on the server where MySQL runs) to reset the connection:
`iptables -A INPUT -s  xx.xx.xx.xx -p tcp -m tcp --dport 3306 --sport xxxxx -j REJECT --reject-with tcp-reset`
xx.xx.xx.xx is the IP address of the client. sport is the port of the client's MySQL connection.
4. Do some queries again and it will happen.

### Extra

Here are the data packets I've captured on the production server.
[dump.zip](https://github.com/eclipse-vertx/vertx-sql-client/files/4360794/dump.zip)

**Comment by BillyYccc** [comment]
Hi, from the network dump file I don't see any `FIN` packet, I think the client sent a `STMT_EXECUTE` MySQL specific packet while the connection is half-open so the server responded with a `RST` packet.

I wonder how the idle connection is closed by server and abruptly broken here, I tried with `wait_timeout` but the connection is closed by server correctly.

But the pool lacks of abilities to detect corrupt connections and is something that could be improved in the future.

**Comment by dangfan** [comment]
Hi BillyYccc, thanks for your reply. From my experiment, the proxysql did respond with a `RST` packet.

So is there any way to know this since it cannot be caught by `try-catch`? When this happens, my verticle just hangs there :(

Thanks!

**Comment by BillyYccc** [comment]
If the connections are frequently closed by the server I think it's better to avoid connection pooling and use `MySQLConnection` directly instead, so when you finish using the connection you can just close it from the client side by calling `MySQLConnection#close()`.

**Comment by dangfan** [comment]
Thank you very much! Do you think we need to remain this issue open since this might be improved in the future?

**Comment by BillyYccc** [comment]
I will close this because it seems there's nothing could be done for the mysql client to handle the RST at present.

**Comment by BillyYccc** [comment]
see https://github.com/eclipse-vertx/vertx-sql-client/issues/837.
