### ISSUE TITLE
PreparedStatement bicommand scheduling on pool are not scheduled on the same connection

### ISSUE THREAD

**Issue by BillyYccc** [eclipse-vertx/vertx-sql-client#590]
### Version

this should happen in `3.9` version

### Context

We meet such exceptions when we use `SqlClient#preparedQuery`

```
o.vertx.mysqlclient.MySQLException: Unknown prepared statement handler (1) given to mysqld_stmt_execute
	at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:28)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:58)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:100)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:65)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:54)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

One-shot prepared statement executing will schedule a `PrepareStatementCommand` and `ExtendedQueryCommand` like this
https://github.com/eclipse-vertx/vertx-sql-client/blob/f44980366fe1ae34714ee1989635d8c8fea2f416/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SqlClientBase.java#L100-L116

such two commands may be scheduled on the different connections acquired from the pool, we should make sure the BiCommand scheduling happen on the same session

### Do you have a reproducer?

see https://groups.google.com/forum/?fromgroups#!topic/vertx/KAdcC_yNG8E
This also happens in https://travis-ci.org/github/eclipse-vertx/vertx-sql-client/jobs/674432633

A simple snippet of code could reproduce this
```
// set pool size to 2
  @Test
  public void highContendPreparedQuery(TestContext ctx) {
    Async async = ctx.async(15000);
    for (int i = 0; i < 15000; i++) {
      pool.preparedQuery("SELECT " + i).execute(ctx.asyncAssertSuccess(res -> {
        async.countDown();
      }));
    }
    async.await();
  }
```

**Comment by vietj** [comment]
did you work on this issue @BillyYccc ?

**Comment by BillyYccc** [comment]
not yet, but I hope we can settle this in 3.9.1

Julien Viet <notifications@github.com> 于 2020年5月11日周一 18:44写道：

**Comment by vietj** [comment]
Any chance by tomorrow ?

**Comment by BillyYccc** [comment]
I'll hava a try tonight

Julien Viet <notifications@github.com> 于 2020年5月11日周一 19:21写道：

> Any chance by tomorrow ?
>

**Comment by vietj** [comment]
I will handle this one @BillyYccc

**Comment by vietj** [comment]
funny there is already such similar test in PgPoolTest

**Comment by vietj** [comment]
the fix is easy, I'm almost done with it. I'll port the test to master as well.
