### ISSUE TITLE
error using prepared statement cache with DB2

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#671]
When I enable the prepared statement cache with DB2 in the HR test suite, I get an error.

I *think* the root cause is this:

```
[2020-06-02 20:24:03] SEVERE io.vertx.db2client.impl.codec.DB2Encoder                FATAL: Unable to encode command: io.vertx.sqlclient.impl.command.CloseStatementCommand@501e333e
java.util.ConcurrentModificationException
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.vertx.db2client.impl.codec.DB2PreparedStatement.close(DB2PreparedStatement.java:101)
	at io.vertx.db2client.impl.codec.CloseStatementCommandCodec.encode(CloseStatementCommandCodec.java:31)
	at io.vertx.db2client.impl.codec.DB2Encoder.write(DB2Encoder.java:79)
	at io.vertx.db2client.impl.codec.DB2Encoder.write(DB2Encoder.java:63)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:697)
	at io.vertx.sqlclient.impl.SocketConnectionBase.checkPending(SocketConnectionBase.java:177)
	at io.vertx.sqlclient.impl.SocketConnectionBase.schedule(SocketConnectionBase.java:165)
	at io.vertx.db2client.impl.DB2SocketConnection.schedule(DB2SocketConnection.java:70)
	at io.vertx.sqlclient.impl.Connection.schedule(Connection.java:34)
	at io.vertx.sqlclient.impl.cache.PreparedStatementCache.lambda$new$0(PreparedStatementCache.java:38)
	at io.vertx.sqlclient.impl.cache.LruCache.removeEldestEntry(LruCache.java:38)
	at java.util.LinkedHashMap.afterNodeInsertion(LinkedHashMap.java:299)
	at java.util.HashMap.putVal(HashMap.java:663)
	at java.util.HashMap.put(HashMap.java:611)
	at io.vertx.sqlclient.impl.cache.InflightCachingStmtEntry.handle(InflightCachingStmtEntry.java:40)
	at io.vertx.sqlclient.impl.cache.InflightCachingStmtEntry.handle(InflightCachingStmtEntry.java:21)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:188)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:78)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.vertx.db2client.impl.codec.DB2Encoder.lambda$write$0(DB2Encoder.java:75)
	at io.vertx.db2client.impl.codec.PrepareStatementCodec.handleReadyForQuery(PrepareStatementCodec.java:89)
	at io.vertx.db2client.impl.codec.PrepareStatementCodec.handleColumnDefinitionsDecodingCompleted(PrepareStatementCodec.java:101)
	at io.vertx.db2client.impl.codec.PrepareStatementCodec.decodePayload(PrepareStatementCodec.java:80)
	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:80)
	at io.vertx.db2client.impl.codec.DB2Decoder.decode(DB2Decoder.java:53)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vietj** [comment]
can you look at this @aguibert ?

**Comment by aguibert** [comment]
yep, I can look into this

**Comment by vietj** [comment]
it would be best if we can fix it for 3.9.2 timeframe.

**Comment by aguibert** [comment]
@gavinking having a look at this one now. I enabled prepared statement caching in hrx and I indeed see errors, but I'm getting SQLCode -313 errors instead of the ConcurrentModificationException you originally described. The -313 is certainly a problem so I'll dig into that issue first and hopefully it's the only problem

**Comment by gavinking** [comment]
Excellent, thanks.

On Wed, Jul 1, 2020 at 5:29 PM Andrew Guibert <notifications@github.com> wrote:
>
> @gavinking having a look at this one now. I enabled prepared statement caching in hrx and I indeed see errors, but I'm getting SQLCode -313 errors instead of the ConcurrentModificationException you originally described. The -313 is certainly a problem so I'll dig into that issue first and hopefully it's the only problem
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Gavin King
IBM

**Comment by gavinking** [comment]
Any update in this one? I would love to be able to remove our workaround in HR? Sorry for nagging.
