### ISSUE TITLE
Postgres: Cannot determine data type of String in TRIM() function

### ISSUE THREAD

**Issue by AugustNagro** [eclipse-vertx/vertx-sql-client#699]
### Version

4.0.0-SNAPSHOT

### Context

I noticed recently that the Postgres Client cannot determine the data type of the more-advanced `trim` variant (https://www.postgresql.org/docs/current/functions-string.html), throwing

```
io.vertx.pgclient.PgException: { "message": "could not determine data type of parameter $1", "severity": "ERROR", "code": "42P18", "file": "postgres.c", "line": "1466", "routine": "exec_parse_message" }

	at io.vertx.client.sql.pg@4.0.0-SNAPSHOT/io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
	at io.vertx.client.sql.pg@4.0.0-SNAPSHOT/io.vertx.pgclient.impl.codec.PrepareStatementCommandCodec.handleErrorResponse(PrepareStatementCommandCodec.java:71)
	at io.vertx.client.sql.pg@4.0.0-SNAPSHOT/io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:232)
	at io.vertx.client.sql.pg@4.0.0-SNAPSHOT/io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:122)
	at io.vertx.client.sql.pg@4.0.0-SNAPSHOT/io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### Steps To Reproduce

With this table,

```sql
create table test_person (
    id bigserial primary key,
    first_name varchar(50),
    last_name varchar(50) not null,
    is_admin boolean default true
);

insert into test_person (first_name, last_name, is_admin) values
('George', 'Washington', true),
('Alexander', 'Hamilton', true),
('John', 'Adams', true),
('Benjamin', 'Franklin', true),
('John', 'Jay', true),
('Thomas', 'Jefferson', true),
('James', 'Madison', true),
('August', 'Nagro', false);
```

The following test fails:

```java
  @Test
  void testTrim(VertxTestContext ctx) {
    pool.preparedQuery("SELECT * FROM test_person WHERE (TRIM(LEADING '$1' FROM last_name) = $2)")
        .execute(Tuple.of("W", "ashington"))
        .onComplete(ctx.succeeding(rs -> ctx.verify(() -> {
          assertEquals(1, rs.size());
          ctx.completeNow();
        })));
}
```

**Comment by AugustNagro** [comment]
Also have tried with a longer predicate without success.

```
WHERE (CONCAT(first_name, last_name) = $1) AND (CONCAT(first_name, last_name) = $2) AND (CONCAT(CONCAT(first_name, $3), $4) = $5)


io.vertx.pgclient.PgException: { "message": "could not determine data type of parameter $3", "severity": "ERROR", "code": "42P18", "file": "postgres.c", "line": "1466", "routine": "exec_parse_message" }

```

**Comment by vietj** [comment]
this looks like a Postgres issue, can you try with another client like JDBC ?

**Comment by AugustNagro** [comment]
My first query with TRIM does not work in either client. This one works in JDBC:

```java
    try (Connection con = DriverManager.getConnection("jdbc:postgresql://localhost/test", "august", null)) {
      String query = "SELECT COUNT(*) FROM test_person WHERE (concat(first_name, ?) = ?)";
      PreparedStatement ps = con.prepareStatement(query);
      ps.setObject(1, "Washington");
      ps.setObject(2, "GeorgeWashington");
      ResultSet rs = ps.executeQuery();
      rs.next();
      System.out.println(rs.getLong(1));
    }
```

But not vertx-sql-client:

```java
  @Test
  void helloWorld(VertxTestContext ctx) {
    pool.preparedQuery("SELECT COUNT(*) FROM test_person WHERE (CONCAT(first_name, $1) = $2)")
        .execute(Tuple.of("Washington", "GeorgeWashington"))
        .onComplete(ctx.succeeding(rs -> ctx.verify(() -> {
          assertEquals(1, rs.iterator().next().getLong(0));
          ctx.completeNow();
        })));
  }
```

**Comment by vietj** [comment]
I will have a look, thanks for the case

**Comment by vietj** [comment]
this works if you cast $1 to VARCHAR, i.e the query is "SELECT COUNT(*) FROM test_person WHERE (CONCAT(first_name, $1 :: VARCHAR) = $2)"

if you don't do that then Postgres cannot infer the type of $1 from the query, I don't know how this is implemented with PosgreSQL, perhaps it is rewritten this way

**Comment by BillyYccc** [comment]
Sometimes the parameter data types inferred by the server in the statement PREPARE response might vary from the intented data types of the original usage.

In MySQL and SQL Server the parameter data types are inferred from the parameters values which means they're binded dynamically in the execution.

FYI there is a similar case when the provided inferred data type causes unexpected behaviors. https://github.com/vietj/reactive-pg-client/issues/11

**Comment by vietj** [comment]
I will try to improve this and provide PreparedStatementCommand the types used when the first prepare is executed:

- with one-shot queries this is trivial to do (with the latest flow refactor)
- with explicitly prepared statement then for PostgreSQL the specific `42P18` would be caught and the prepared statement prepared would be delayed until it is first executed, that would be a specific PostgreSQL implementation

**Comment by vietj** [comment]
Now I wish Java had variadic tuples like Ceylon to one could write `Future<PreparedStatement<String, Integer>> fut = conn.prepare<String, Integer>("some sql")` :-)

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vertx-sql-client/pull/704 and https://github.com/eclipse-vertx/vertx-sql-client/pull/703 for WIP

**Comment by AugustNagro** [comment]
Awesome, just tested out 703 and can confirm it fixes the problem.

**Comment by AugustNagro** [comment]
Just wanted to share, I'm making a little annotation processor that emulates some features from Spring Data Repositories. Writing tests for its Specification-esque api is how I found the bug.

https://github.com/AugustNagro/vertx-repo

Cheers!

**Comment by vietj** [comment]
@AugustNagro it looks great, you should add it to Vert.x Awesome page https://github.com/vert-x3/vertx-awesome
