### ISSUE TITLE
NullPointerException when listening to postgresql notifications and disconnected from db

### ISSUE THREAD

**Issue by steven-sheehy** [eclipse-vertx/vertx-sql-client#713]
### Questions

N/A

### Version

3.9.1

### Context

I'm testing reconnect of PgSubscriber/PgChannel by shutting down PostgreSQL while listening to a channel for messages. When I do so, I get a NPE that occurs periodically. Possibly some race condition:

```
java.lang.NullPointerException
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:233)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:122)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Do you have a reproducer?

No

### Steps to reproduce

1. Run code
```java
        PgSubscriber subscriber = PgSubscriber.subscriber(Vertx.vertx(), connectOptions)
                .reconnectPolicy(retries -> {
                    return 1000L;
                });

        subscriber.connect(connectResult -> {
            if (connectResult.failed()) {
                throw new RuntimeException(connectResult.cause());
            }
            log.info("Connected to database");
        });

        subscriber.channel("topic_message").handler(json -> log.info("json: {}", json));
```
2. Shutdown PostgreSQL
3. Start and stop PostgreSQL until it occurs as it doesn't occur every time

### Extra

MacOS 10.15.4 (Catalina)
OpenJDK 11

**Comment by vietj** [comment]
See https://github.com/eclipse-vertx/vertx-sql-client/issues/731
