### ISSUE TITLE
ConnectionPool is not thread-safe

### ISSUE THREAD

**Issue by nosov89** [eclipse-vertx/vertx-sql-client#717]
Version 3.9.1. ConnectionPool use ArrayDeque, that is not thread-safe and requires external synchronization.
Private method check is also not thread-safe.

StackTrace:

java.lang.NullPointerException: null
at io.vertx.sqlclient.impl.ConnectionPool.check(ConnectionPool.java:196)
at io.vertx.sqlclient.impl.ConnectionPool.acquire(ConnectionPool.java:75)
at io.vertx.sqlclient.impl.PoolBase.schedule(PoolBase.java:88)
at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.execute(SqlClientBase.java:103)
at io.vertx.kotlin.sqlclient.PreparedQueryKt$executeAwait$4.invoke(PreparedQuery.kt:45)
at io.vertx.kotlin.sqlclient.PreparedQueryKt$executeAwait$4.invoke(PreparedQuery.kt)
at io.vertx.kotlin.coroutines.VertxCoroutineKt.awaitEvent(VertxCoroutine.kt:51)
at io.vertx.kotlin.coroutines.VertxCoroutineKt.awaitResult(VertxCoroutine.kt:81)
at io.vertx.kotlin.sqlclient.PreparedQueryKt.executeAwait(PreparedQuery.kt:44)

**Comment by nosov89** [comment]
not a bug, incorrect usage of vertx
