### ISSUE TITLE
Transactions get stuck with a nullpointer

### ISSUE THREAD

**Issue by meredrica** [eclipse-vertx/vertx-sql-client#721]
Hello!
We are using the library via Micronaut 2.0.1 and noticed the following behaviour:
We have a long running read transaction that is streamed back to the client via rxjava 2.
Queries can run several minutes (which is expected) however: When the HTTP connection to our backend is closed, we get nullpointers and the transaction in postgres is stuck as ``idle in transaction``.
I'm sorry that I can't provide a reproducer, it's a large project.

This is how we read the data:

``` java
public Observable<DomainObject> stream() {
    return pgPool
        .rxBegin()
        .flatMapObservable(
            tx -> {
              UUID id = UUID.randomUUID();
              log.debug("preparing query {} (this is not a real id)", id);
              return tx.rxPrepare(query.sql())
                  .flatMapObservable(
                      prepared ->
                          prepared
                              .createStream(10, query.parameters())
                              .toObservable()
                              .map(
                                  row -> {
                                    // FIXME: this should maybe be set to trace
                                    log.debug("mapping for query {}", id);
                                    return mapRowToDomainObject(row);
                                  }))
                  .doFinally(
                      () -> {
                        log.debug("commiting query {}", id);
                        tx.commit();
                        log.debug("done with query {}", id);
                      });
            });
  }
```

and here is the exception:

```
java.lang.NullPointerException
--
  | at io.vertx.sqlclient.impl.RowStreamImpl.checkPending(RowStreamImpl.java:174)
  | at io.vertx.sqlclient.impl.RowStreamImpl.handle(RowStreamImpl.java:129)
  | at io.vertx.sqlclient.impl.RowStreamImpl.handle(RowStreamImpl.java:30)
  | at io.vertx.sqlclient.impl.SqlResultHandler.complete(SqlResultHandler.java:97)
  | at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:86)
  | at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
  | at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:213)
  | at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:83)
  | at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
  | at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
  | at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
  | at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
  | at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
  | at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
  | at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
  | at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  | at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
  | at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
  | at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:138)
  | at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:226)
  | at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:86)
  | at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
  | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
  | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  | at java.base/java.lang.Thread.run(Thread.java:834)
```
relevant ``mvn dependency:tree``

```
[INFO] +- io.micronaut.sql:micronaut-vertx-pg-client:jar:2.3.6:compile
[INFO] |  +- io.vertx:vertx-pg-client:jar:3.9.1:compile
[INFO] |  |  +- io.vertx:vertx-core:jar:3.9.1:compile
[INFO] |  |  |  \- io.netty:netty-resolver-dns:jar:4.1.48.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-dns:jar:4.1.48.Final:compile
[INFO] |  |  \- io.vertx:vertx-sql-client:jar:3.9.1:compile
```

We do see in our logs the 'tx done' part but we get the nullpointer afterwards.

**Comment by vietj** [comment]
@meredrica would you mind to provide a reproducer project to help us investigate ?
