### ISSUE TITLE
batching on DB2

### ISSUE THREAD

**Issue by gavinking** [eclipse-vertx/vertx-sql-client#723]
I had to disable [this test](https://github.com/hibernate/hibernate-reactive/blob/04d999bafcba2b3abdd14ddeed3be1a5c18d1e5f/hibernate-reactive-core/src/test/java/org/hibernate/reactive/BatchQueryOnConnectionTest.java) in Hibernate Reactive on DB2, due to the following error:

```
 java.lang.IllegalStateException: Found unknown codepoint: 0x220a / 8714
            at io.vertx.db2client.impl.drda.DRDAResponse.throwUnknownCodepoint(DRDAResponse.java:847)
            at io.vertx.db2client.impl.drda.DRDAConnectResponse.parseCommonError(DRDAConnectResponse.java:121)
            at io.vertx.db2client.impl.drda.DRDAQueryResponse.parseExecuteError(DRDAQueryResponse.java:1079)
            at io.vertx.db2client.impl.drda.DRDAQueryResponse.parseEXCSQLSTTreply(DRDAQueryResponse.java:582)
            at io.vertx.db2client.impl.drda.DRDAQueryResponse.readExecute(DRDAQueryResponse.java:238)
```

**Comment by aguibert** [comment]
thanks for reporting this one, I'll look into it and at min get the codepoint documented so users get a proper error message.

**Comment by gavinking** [comment]
Oh, geez, my apologies @aguibert, I just realized that this problem isn't related to batching at all. It's something to do with `BigDecimal`. I should have looked more closely at the time!

**Comment by gavinking** [comment]
@aguibert I was able to re-enable the test after making this change:

<https://github.com/hibernate/hibernate-reactive/commit/546a22c08af552804c09ad0fa80ba1617207e284>

Apparently the driver chokes on certain numerical values of the `BigDecimal`.

**Comment by aguibert** [comment]
ah, yea I've spent many hours debugging decimal issues. 

Here is the relevant documentation for DB2 decimal number precision:
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0008469.html

DB2 uses [IBM hexadecimal floating point format](https://en.wikipedia.org/wiki/IBM_hexadecimal_floating_point) which is different than IEEE 754 which pretty much everything else uses.

To be clear though, the stacktrace in the OP is what you get when you try to store this certain BigDecimal value?

**Comment by gavinking** [comment]
> the stacktrace in the OP is what you get when you try to store this certain BigDecimal value?

Yup.
