### ISSUE TITLE
Unable to write MultiPolygon to MySQL 

### ISSUE THREAD

**Issue by anuranjit** [eclipse-vertx/vertx-sql-client#748]
### Questions
Unable to write MultiPolygon to MySQL . Polygon class works but Multipolygon does not. Below is the GeoJson for that .
```
{
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                74.15771484375,
                23.034242642076585
              ],
              [
                73.4930419921875,
                22.156883186860703
              ],
              [
                73.6688232421875,
                21.151115354148047
              ],
              [
                75.74523925781249,
                21.130621534363144
              ],
              [
                76.7230224609375,
                22.39579284633252
              ],
              [
                74.15771484375,
                23.034242642076585
              ]
            ],
            [
              [
                74.37744140625,
                22.421184710331858
              ],
              [
                75.025634765625,
                22.294179051660386
              ],
              [
                74.432373046875,
                21.83600579798428
              ],
              [
                74.37744140625,
                22.421184710331858
              ]
            ]
          ],
          [
            [
              [
                76.3330078125,
                23.74009762440226
              ],
              [
                75.6298828125,
                23.23125092389779
              ],
              [
                76.893310546875,
                22.740723091194727
              ],
              [
                76.3330078125,
                23.74009762440226
              ]
            ]
          ]
        ]
      }
```
### Version
Vertx version 4.0.0.Beta1, MySQL Version 8 ,Java 11

Error from mysql .
```
io.vertx.mysqlclient.MySQLException: Cannot get geometry object from data you send to the GEOMETRY field
io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:38)
```

**Comment by vietj** [comment]
@anuranjit can you provide a reproducer ?

**Comment by anuranjit** [comment]
https://github.com/anuranjit/starter @vietj . This requires mysql 8

**Comment by anuranjit** [comment]
@vietj Are you able to access the project . ?

**Comment by BillyYccc** [comment]
I'll take a look

**Comment by BillyYccc** [comment]
@anuranjit I got this exception while testing, it seems the geo data object provided in the json is in an invalid format.
```
io.vertx.mysqlclient.MySQLException: Invalid GIS data provided to function st_geometryfromwkb.

	at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.handleRows(QueryCommandBaseCodec.java:108)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:67)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:109)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:77)
```

**Comment by anuranjit** [comment]
@BillyYccc What is the MYSQL version you are using. 
I am using vertx 4.0.0.Beta1 and mysql 8 . 
Just did `./gradlew run` and `curl localhost:8888`  
My Stack trace is this and not the above one. 

```

io.vertx.mysqlclient.MySQLException: Cannot get geometry object from data you send to the GEOMETRY field
        at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
        at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:38)
        at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:57)
        at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:100)
        at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:77)
        at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:66)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by anuranjit** [comment]
Found the issue . It was actually the schema in the MySQL which was wrong .
