### ISSUE TITLE
[PostgreSQL] Connections are not returned/closed and max pool size is not honored.

### ISSUE THREAD

**Issue by meredrica** [eclipse-vertx/vertx-sql-client#796]
### Context
I would call this a follow up to #721 
We're using micronaut as the backend and stream data from the database to the client via REST, using flowables.
The database code looks like this:

```java
public Flowable<DomainObject> stream() {
    return pgPool
        .rxBegin()
        .toFlowable()
        .concatMap(
            tx -> {
              return tx.rxPrepare(query.sql())
                  .toFlowable()
                  .concatMap(
                      prepared ->
                          prepared
                              .createStream(10, query.parameters())
                              .toFlowable()
                              .map(
                                  row -> {
                                    return mapRowToDomainObject(row);
                                  }))
                  .doOnError(e -> log.error("got error", e))
                  .doAfterTerminate(
                      () -> {
                        tx.commit();
                      });
            });
  }
```
If the HTTP request is cancelled, the connection is not returned to the pool and stays open indefinitely. The pool will grow and gradually drain the max connection limit on our postgresql database.
The ``doOnError`` callback is never called so I don't see a way to work around this on our side.
I tried to manage the connection myself but ran into other troubles and gave up on that.

### Do you have a reproducer?

Nothing but the code above.

### Steps to reproduce

Create a long running query and stream the results via micronaut. While the HTTP Request is in flight, kill it.
Then execute ``select usename, count(*) from pg_stat_activity;`` in postgres and see the connection hang.

### Extra
I tried playing around with the max pool size, max wait queue etc. The problem persists.

### Stacktrace
``` java
java.lang.IllegalStateException: No current cursor read
at io.vertx.sqlclient.impl.CursorImpl.hasMore(CursorImpl.java:54)
at io.vertx.sqlclient.impl.RowStreamImpl.checkPending(RowStreamImpl.java:200)
at io.vertx.sqlclient.impl.RowStreamImpl.handle(RowStreamImpl.java:146)
at io.vertx.sqlclient.impl.RowStreamImpl.handle(RowStreamImpl.java:32)
at io.vertx.sqlclient.impl.SqlResultHandler.complete(SqlResultHandler.java:98)
at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:87)
at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:239)
at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:86)
at io.vertx.core.net.impl.NetSocketImpl.lambda$new$2(NetSocketImpl.java:101)
at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:127)
at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:357)
at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:163)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:78)
at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:138)
at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:226)
at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:86)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
```

### Version

``mvn dependency:tree`` gives latest:
```mvn
[INFO] +- io.micronaut.sql:micronaut-vertx-pg-client:jar:3.2.0:compile
[INFO] |  +- io.vertx:vertx-pg-client:jar:3.9.4:compile
[INFO] |  |  +- io.vertx:vertx-core:jar:3.9.4:compile
[INFO] |  |  |  \- io.netty:netty-resolver-dns:jar:4.1.53.Final:compile
[INFO] |  |  |     \- io.netty:netty-codec-dns:jar:4.1.53.Final:compile
[INFO] |  |  \- io.vertx:vertx-sql-client:jar:3.9.4:compile
[INFO] |  +- io.vertx:vertx-rx-java2:jar:3.9.4:compile
[INFO] |  |  \- io.vertx:vertx-rx-gen:jar:3.9.4:compile
[INFO] |  \- io.vertx:vertx-codegen:jar:3.9.4:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.11.2:compile
[INFO] |     \- org.mvel:mvel2:jar:2.3.1.Final:compile
```
### Settings
```yaml
vertx:
    pg:
        client:
            max-size: 4
            idle-timeout: 5
            max-wait-queue-size: 4
            uri: jdbc:postgres....
            prepared-statement-max-cache-size: 1
```

**Comment by meredrica** [comment]
After removing several subscribeOn/observeOn pieces we now have this stacktrace, even without killing the http request. This now happens every time, which drains the pool even faster than before and actually produces wrong json output (but that's a micronaut problem)
```
WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by io.micronaut.http.netty.reactive.HandlerSubscriber$$Lambda$959/0x000000010083c840.operationComplete()
java.lang.IllegalStateException: null
at io.vertx.sqlclient.impl.SocketConnectionBase.schedule(SocketConnectionBase.java:135)
at io.vertx.sqlclient.impl.ConnectionPool$PooledConnection.schedule(ConnectionPool.java:117)
at io.vertx.sqlclient.impl.PreparedStatementImpl.lambda$closeCursor$5(PreparedStatementImpl.java:201)
at io.vertx.core.impl.SucceededFuture.onComplete(SucceededFuture.java:41)
at io.vertx.sqlclient.impl.PreparedStatementImpl.closeCursor(PreparedStatementImpl.java:197)
at io.vertx.sqlclient.impl.CursorImpl.close(CursorImpl.java:103)
at io.vertx.sqlclient.Cursor.close(Cursor.java:52)
at io.vertx.sqlclient.impl.RowStreamImpl.checkPending(RowStreamImpl.java:205)
at io.vertx.sqlclient.impl.RowStreamImpl.fetch(RowStreamImpl.java:110)
at io.vertx.sqlclient.impl.RowStreamImpl.fetch(RowStreamImpl.java:32)
at io.vertx.reactivex.impl.FlowableReadStream$1.request(FlowableReadStream.java:61)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:135)
at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.request(FlowableConcatMap.java:237)
at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.request(FlowableDoFinally.java:107)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:135)
at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.request(FlowableConcatMap.java:237)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.operators.flowable.FlowableDoFinally$DoFinallySubscriber.request(FlowableDoFinally.java:107)
at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
at io.reactivex.internal.subscriptions.SubscriptionArbiter.request(SubscriptionArbiter.java:135)
at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
at io.reactivex.internal.subscribers.BasicFuseableSubscriber.request(BasicFuseableSubscriber.java:153)
at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:219)
at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
at io.micronaut.http.netty.reactive.HandlerSubscriber.maybeRequestMore(HandlerSubscriber.java:215)
at io.micronaut.http.netty.reactive.HandlerSubscriber.lambda$onNext$0(HandlerSubscriber.java:177)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.util.concurrent.PromiseCombiner.tryPromise(PromiseCombiner.java:170)
at io.netty.util.concurrent.PromiseCombiner.access$600(PromiseCombiner.java:35)
at io.netty.util.concurrent.PromiseCombiner$1.operationComplete0(PromiseCombiner.java:62)
at io.netty.util.concurrent.PromiseCombiner$1.operationComplete(PromiseCombiner.java:44)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717)
at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272)
at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:431)
at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898)
at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by chris-brace** [comment]
I'm not using micronaut and this is happening to me in a production environment. When enough transactions are rolled back, the pool just starts checking out new connections until the DB is maxed out.

**Comment by vietj** [comment]
thanks we will investigate, does the code above reproduces consistently ?

**Comment by chris-brace** [comment]
I did a several thousand line refactor of how we were using the pg driver to get 3.9.4 and pushed it to a customer UAT environment. the same behavior persists (many more connections being checked out than the max pool size should allow) after many transaction rollbacks.

**Comment by vietj** [comment]
I will have a look soon @chris-brace

**Comment by chris-brace** [comment]
@vietj i really appreciate it. i just spent a few hours building a simulator that creates / commits / and rolls back transactions at a rate and in a pattern similar to how our real ETL system works but i could not get it to create more connections than the max count given to the pool. I *can* reproduce this behavior locally on my machine on command but I am at a loss for how exactly to show this to you because it contains very, very larges amounts of proprietary information XD I will continue to try to trigger it in a test project but this is the information i have right now:

Transactions that are allocated beyond the pools maximum get left in an idle state and their most recent query was ROLLBACK according to the `pg_stat_activity` table. As far as i can tell, 70000 transactions that generates ~20000 rollbacks of varying causes creates exactly the same amount of "orphaned" connections as there are exceptions of type `PgException` with message `value too long for type character varying(2)`

Ill keep trying to make a sharable reproduction.

**Comment by vietj** [comment]
@chris-brace by stack trace do you mean the first one mentioned in this issue or the second one ?

**Comment by vietj** [comment]
@meredrica can you elaborate how the first stack trace you mention appears, is it because of the code you pasted or because of `select usename, count(*) from pg_stat_activity;`. It is not clear how things are related and complicated for me to put up something that would reproduce it.

**Comment by vietj** [comment]
@meredrica if something wrong happens in the HTTP layer, the stream subscription should be cancelled, does it happen in practice ?

**Comment by vietj** [comment]
@chris-brace a reproducer would definitely help here

**Comment by chris-brace** [comment]
I did it! I have a repro! https://github.com/chris-brace/transaction-repro

change these lines https://github.com/chris-brace/transaction-repro/blob/main/src/main/java/ai/brace/transaction_test/MainVerticle.java#L34-L37 and run main.

you'll see that it opens 80 connections (at least on my machine) nearly immediately and throws an illegalstateexception in PooledConnection.close, too.

if you switch this line to `dontDoAnythingBad()` 
https://github.com/chris-brace/transaction-repro/blob/main/src/main/java/ai/brace/transaction_test/MainVerticle.java#L168
you will see that it runs forever, adding rows to the table that it sets up at the beginning without ever making more than 10 connections. 

The best i can do to explain whats happening here is that you're making two queries which BOTH cause psql to throw an error on insert. However, CompositeFuture.all(a, b) is chained with a onFailure() function which, on the FIRST failure, calls ROLLBACK on the transaction. I am assuming that the response from the SECOND failure is causing the driver to get confused somehow.

The entire repro is in that one main.java file and im pretty sure that im not doing anything here which should be explicitly disallowed from a client programmers perspective.

**Comment by chris-brace** [comment]
If you change the `tx()` function in my code to 
```java
  <T> Future<?> tx(Function<Transaction, Future<T>> mapper)
  {
    final Promise<Void> ret = Promise.promise();
    final Promise<Transaction> txp = Promise.promise();
    pool.begin(txp);
    txp.future()
       .compose(tx -> mapper.apply(tx)
                            .onFailure(ret::fail)
                            .onSuccess(ignored -> tx.commit(ret)));

    return ret.future();
  }
```

the problem entirely goes away. its really unclear when / how you're supposed to call rollback(), frankly. And i wonder if the fact that i was apparently misusing it means that @meredrica is triggering code thats also misusing it or close()

**Comment by vietj** [comment]
@chris-brace that is possible.

I'll look at your reproducer and see if there is an actual bug (I think there might be).

I think that we should provide a method returning a stream that would automatically manage the transaction for you.

**Comment by vietj** [comment]
it also disappear when `blowUp` is called once instead of two

**Comment by vietj** [comment]
I created this test in Sql client test suite that reproduces it

```java
  @Test
  public void testReproducer(TestContext ctx) {
    Async async = ctx.async();
    connector.accept(ctx.asyncAssertSuccess(tx -> {
      List<Future> futures = new ArrayList<>();
      for (int i = 0;i < 2;i++) {
        Promise promise = Promise.promise();
        futures.add(promise.future());
        tx.query("SELECT whatever from DOES_NOT_EXIST").execute(promise);
      }
      CompositeFuture.all(futures).onComplete(ar -> {
        if (ar.succeeded()) {
          tx.commit(ctx.asyncAssertSuccess(v -> {
            async.complete();
          }));
        } else {
          tx.rollback(ctx.asyncAssertSuccess(v -> {
            async.complete();
          }));
        }
      });
    }));
  }
```

indeed, there should be a check based on state that a connection is not closed twice on a rollback.

In Vert.x 4 there is a new construct `withTransaction` to simplify this and let the user not care of the actual transaction boundaries. That would not work with streams though, however we could have something similar as I explained above.

**Comment by vietj** [comment]
that being said, this faulty behavior seems different than the one reported in this issue with the cursor.

**Comment by vietj** [comment]
here is a simpler reproducer:

```java
  @Test
  public void testReproducer(TestContext ctx) {
    Async async = ctx.async();
    connector.accept(ctx.asyncAssertSuccess(tx -> {
      tx.query("SELECT whatever from DOES_NOT_EXIST").execute(ctx.asyncAssertFailure());
      tx.query("SELECT 1").execute(ctx.asyncAssertFailure(err -> {
        tx.rollback(ctx.asyncAssertFailure(v -> {
          // Already rolled back
          async.complete();
        }));
      }));
    }));
  }
````

This test adds 2 queries to the same transaction and add the second before the result of the first query (thing that is not possible with synchronous API, unless 2 threads are used).

When the first query is executed, the transaction is rolled backed and with the current implementation it will fail all the pending queries (See `TransactionImpl#wrap` method) *before* the transaction is rolled back (same method after).

This test will rollback the transaction in the completion handler of the 2nd query and then the transaction will try to roll back the transaction. This will result in 2 callbacks that will both try to return the connection to the pool and the 2nd one will fail with an `IllegalStateException`.

**Comment by chris-brace** [comment]
> that being said, this faulty behavior seems different than the one reported in this issue with the cursor.

Yes please let me know if i should open a separate bug. The reason I ended up here was because it was the only bug i could find by googling that had anything to do with more connections being left open than the max pool size allowed. Given the usage of micronaut and flowable code its highly likely that there are two different issues at play here. 

So, the punchline here is that for the past year I have been writing a lightweight, highly opinionated ORM specifically dependent on vertx's postgres client which I hope to open source some time soon. We're using it internally in production. Do you have any guidance on how (if at all) i should change my usage of the transaction object here?

```java
    public static <T> Future<T> transaction(final Function<Transaction, Future<T>> mapper)
    {
        final StackWalker.StackFrame[] stack = StackWalker.getInstance().walk(Query::walkStack);

        return startTransaction().compose(tx -> {
            final Future<T> mapResult;

            try
            {
                mapResult = mapper.apply(tx);
            }
            catch (Throwable t)
            {
                tx.close();
                transactionInvocationError(stack, t);
                return Future.failedFuture(t);
            }

            return mapResult.compose(result -> commitTransaction(tx).map(result)).onFailure(throwable -> {
                tx.close();
                transactionResultChainFailure(stack, throwable);
            });
        });
    }
```

I guess I am still unclear as to how, in my code, "rollback" is getting automatically invoked even when i dont call close() or rollback().

I am surprised that years of development never caused this to happen until we started getting really high throughput in our ETL code.

**Comment by meredrica** [comment]
@vietj 
First of all, thanks for looking into this. 2nd: we had to switch to JDBC because this problem was endangering several huge rollouts :/. I'll answer all the questions you posted out of memory:
About the query:
It's a query that fetches large amounts of data from the DB, several thousand lines and streams it to the HTTP layer. Those queries can run for minutes if need be, so we need to detect the connection drop (which we could, reliably). While I can't guarantee that we cancelled the subscription, I'm fairly certain that we did. The `select usename, count(*) from pg_stat_activity group by usename;` query is just the way you can check for connections that are open inside postgres.
If I'm not mistaken, we saw the connections as `idle` and there was no rollback involved (we only read).

just FYI: using JDBC is a lot slower.

**Comment by vietj** [comment]
@chris-brace I'll open another issue that precisely reflect this, I'll provide a PR soon for 3.9 that you can look at.

I'll try to look into this case after.

**Comment by vietj** [comment]
@chris-brace here is a PR for 3.9 https://github.com/eclipse-vertx/vertx-sql-client/pull/835 can you have a look ?
