### ISSUE TITLE
Text '4714-11-24 00:00:00 BC' could not be parsed at index 20

### ISSUE THREAD

**Issue by SuperPDX** [eclipse-vertx/vertx-sql-client#808]
### Version

vert.x 4.0.0.CR2

jdk 11.0.7

### Context

Caused by: java.time.format.DateTimeParseException: Text '4714-11-24 00:00:00 BC' could not be parsed at index 20

	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948) ~[?:?]
	at java.time.LocalDateTime.parse(LocalDateTime.java:492) ~[?:?]
	at io.vertx.pgclient.impl.codec.DataTypeCodec.<clinit>(DataTypeCodec.java:1036) ~[vertx-pg-client-4.0.0.CR2.jar:4.0.0.CR2]

**Comment by bweinand** [comment]
Same problem here, vert.x 4.0.0.CR1 is fine.
Introduced by: [vertx-sql-client #1036 LocalDateTime.parse("4714-11-24 00:00:00 BC…"](https://github.com/eclipse-vertx/vertx-sql-client/commit/f48daa2803084d2aab33f6d65d5cb102d1c3411b#diff-bf23d08e641edde7ab4f943aafcc621a7f93dc53dab71e6fe62d26796a60de61R1036)
How can the issue be resolved?

macOS Catalina
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11)
OpenJDK 64-Bit Server VM (build 11.0.9+11, mixed mode)

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by vietj** [comment]
This was fixed by https://github.com/eclipse-vertx/vertx-sql-client/commit/a6dba023704e922b02ce6c7dd8e1bb6c23acb417 can you check with latest snapshot ?

**Comment by SuperPDX** [comment]
> This was fixed by [a6dba02](https://github.com/eclipse-vertx/vertx-sql-client/commit/a6dba023704e922b02ce6c7dd8e1bb6c23acb417) can you check with latest snapshot ?

Yes, already fixed ！

In my program Locale.getDefault() is "zh_CN_#Hans"

**Comment by bweinand** [comment]
Checked with latest snapshot and Locale.GERMAN ;-) Thanks!
