### ISSUE TITLE
Connection refused in PgConnectionAutoRetryTest 

### ISSUE THREAD

**Issue by julianladisch** [eclipse-vertx/vertx-sql-client#854]
### Version

Which version(s) did you encounter this bug? 4.0.0, 4.0.1-SNAPSHOT cc3b6c99c7110ad98fd350c3d7f51b997c907305

### Context

Trying to build vertx-pg-client fails in these tests:
PgConnectionAutoRetryTest.testConnRetrySuccess
PgConnectionAutoRetryTest.testConnSuccessWithoutRetry
PgConnectionAutoRetryTest.testPoolRetrySuccess
PgConnectionAutoRetryTest.testPoolSuccessWithoutRetry

```
testConnSuccessWithoutRetry(io.vertx.pgclient.tck.PgConnectionAutoRetryTest)  Time elapsed: 1.022 sec  <<< ERROR!
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /172.17.0.1:45965
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The Exception is reported in
https://github.com/eclipse-vertx/vertx-sql-client/blob/4.0.0/vertx-pg-client/src/test/java/io/vertx/pgclient/tck/ClientConfig.java#L43
https://github.com/eclipse-vertx/vertx-sql-client/blob/4.0.0/vertx-pg-client/src/test/java/io/vertx/pgclient/tck/ClientConfig.java#L65

### Do you have a reproducer?

https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/test/java/io/vertx/pgclient/tck/PgConnectionAutoRetryTest.java

### Steps to reproduce

Build on Jenkins:
https://jenkins-aws.indexdata.com/job/folio-org/job/vertx-sql-client/job/master-vertx/
Complete log is available in the red box in the "Maven build" column.

**Comment by BillyYccc** [comment]
hi I think this is not a bug as the proxy used in the test might fail to listen to the random port in your CI machine, so the client failed to make a connection to it as the stacktrace shows.

**Comment by BillyYccc** [comment]
can you also remove the maintainers of this project from the maillist of your fork repository CI pipeline? :-)

**Comment by julianladisch** [comment]
Sorry for any disruption on your mailinglist, I've removed the upstream files: https://github.com/folio-org/vertx-sql-client/commit/e39b343d584c0a0a7af8aeeff48904423efdd3cd https://github.com/folio-org/vertx-sql-client/commit/721c8060fa33f85ba8d2b743a5654fc3bd185a3e
Please holler if this is not sufficient.
