### ISSUE TITLE
Connection not open CLOSED when connect to mysql for more than 8 hours without operation

### ISSUE THREAD

**Issue by shilei9213** [eclipse-vertx/vertx-sql-client#863]
### Questions

Hi, I got message 'Connection not open CLOSED ', when i use quarkus reactive mysql client  to connect with mysql for more than 8 hours without operation。

I don't know how to solve this problem?

Our mysql  variable 'wait_timeout' is 28800。

Our quarkus config is like this:

```xml quarkus:
  datasource:
      reactive:
      url: 
      reconnect-attempts: 3
      reconnect-interval: PT5S
      max-size: 1
```
 
```xml
      <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-mysql-client</artifactId>
            <version>1.10.3.Final</version>
        </dependency>
```

`2020-12-03 14:36:46,280 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-22) failed to execute statement [select ......]
2020-12-03 14:36:46,281 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-22) could not execute query: java.util.concurrent.CompletionException: io.vertx.core.VertxException: Connection not open CLOSED
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at org.hibernate.reactive.pool.impl.Handlers.lambda$toCompletionStage$0(Handlers.java:29)
        at io.vertx.sqlclient.impl.SqlResultHandler.fail(SqlResultHandler.java:103)
        at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:89)
        at io.vertx.sqlclient.impl.SqlResultHandler.handle(SqlResultHandler.java:33)
        at io.vertx.sqlclient.impl.command.CommandBase.fail(CommandBase.java:31)
        at io.vertx.sqlclient.impl.SocketConnectionBase.schedule(SocketConnectionBase.java:143)
        at io.vertx.sqlclient.impl.ConnectionPool$PooledConnection.schedule(ConnectionPool.java:117)
        at io.vertx.sqlclient.impl.SqlConnectionImpl.schedule(SqlConnectionImpl.java:60)
        at io.vertx.sqlclient.impl.SqlConnectionImpl.lambda$schedule$0(SqlConnectionImpl.java:64)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.vertx.core.VertxException: Connection not open CLOSED
        ... 13 more`

**Comment by BillyYccc** [comment]
hi, it seems that you're using Hibernate reactive, are you opening a session(i.e. using Pool#getConnection) and hold it for a long time but do not close it(return the connection back to the pool)?

**Comment by shilei9213** [comment]
> hi, it seems that you're using Hibernate reactive, are you opening a session(i.e. using Pool#getConnection) and hold it for a long time but do not close it(return the connection back to the pool)?


Thanks for your reply. 

I use quarkus framework and it help me to manage hibernate session and mysql connection .  what do i need to do next to resolve the problem. 

My code is like this:
```java

import io.quarkus.hibernate.reactive.panache.PanacheRepository;
import io.quarkus.panache.common.Parameters;
import io.smallrye.mutiny.Uni;


public abstract class RepositoryBase<Entity> implements PanacheRepository<Entity> {


    public Uni<Void> save(Entity entity) {
        return persistAndFlush(entity);
    }

    public Uni<Integer> logicalDeleteById(Long id, String userName) {
        return update("SET deleted=1 ,update_by=:userName WHERE id=:id", Parameters.with("id", id).and("userName", userName));
    }

}


public class RuleConditionSearchRepositoryBase<T extends RuleFieldBean> extends RepositoryBase<T> {


    @Transactional
    public Uni<List<T>> findAllByConditions(RuleDto ruleCondition) {
        activeContext();
        return buildQuery(ruleCondition, null).list();
    }

   

    private PanacheQuery<T> buildQuery(RuleDto ruleCondition, Sort sort) {
        StringBuilder query = new StringBuilder();
        Parameters parameters = new Parameters();

        if (Objects.nonNull(ruleCondition)) {

            String appId = ruleCondition.getAppId();
            if (StringUtils.isNoneBlank(appId)) {
                query.append(" appId = :appId AND");
                parameters.and("appId", appId);
            }
            

        query.append(" deleted=0");
        if (Objects.isNull(sort)) {
            return find(query.toString(), parameters);
        }
        return find(query.toString(), sort, parameters);
    }


    private void activeContext() {
        ManagedContext requestContext = Arc.container().requestContext();
        if (!requestContext.isActive()) {
            requestContext.activate();
        }
    }
}

```

**Comment by shilei9213** [comment]
> hi, it seems that you're using Hibernate reactive, are you opening a session(i.e. using Pool#getConnection) and hold it for a long time but do not close it(return the connection back to the pool)?

https://www.databasesandlife.com/automatic-reconnect-from-hibernate-to-mysql/

I have known the reason.

Mysql will close the connection when it has been idle over 8 hours.

Our application will close the connection when socket close.

And out application will get VertxException 'Connection not open CLOSED ' when use this connection to query after that.

I'd like to ask about how to remove connection which is closed in the mysql pool and create a new connection ?

**Comment by gavinking** [comment]
Hi, I just read the blog post you linked to, and what this person is doing is just a plain misuse of Hibernate (and JDBC) and it's clear the person who wrote it just doesn't have much knowledge of data access in Java.

You're simply not supposed to _ever_ hold a single Hibernate session or JDBC connection open for such a long time. Ordinarily, these objects are supposed to be opened at the beginning of a transaction, and closed at the end of the transaction. Exceptionally, in some circumstances, it's sometimes OK to hold a session open across a "short" user interaction (a "conversation"), as long as you close it once the interaction is done.

This is not really specific to Hibernate, nor to MySQL, it's just how connections are supposed to be used.

**Comment by gavinking** [comment]
Excuse me, I think I misinterpreted the blog post. My bad, but it's because he didn't actually properly explain what he was doing, and because he goes off on a silly discussion about reconnecting. And so the blog was open to misinterpretation. 

If so, what I wrote isn't quite correct. Sure, it's OK to have a connection open *in the pool* for a long time, in which case it's the job of the pool to make sure you don't have dead connections in the pool. (Again, that isn't specific to Hibernate, nor to c3p0.) 

In the case of c3p0, you would do that by choosing compatible values of `hibernate.c3p0.timeout` and `hibernate.c3p0.idle_test_period`, and I believe an appropriate choice of these properties would have solved the problem described in the blog. In this person's code, you can see that he doesn't set these properties, and doesn't even appear to realize that they exist.

(Aside: I notice from the c3p0 documentation that these days there is also a `maxConnectionAge ` property, which honestly Hibernate should also let you set.)

**Comment by gavinking** [comment]
So for Hibernate Reactive, and the Vert.x SQL client, you should set `hibernate.vertx.pool.idle_timeout`.

In time, we'll probably want to add additional flexibility here. But if the issue is that idle connections are timing out _while in the pool_ then that should fix it.

**Comment by gavinking** [comment]
> So for Hibernate Reactive, and the Vert.x SQL client, you should set `hibernate.vertx.pool.idle_timeout`.
> 
> In time, we'll probably want to add additional flexibility here. But if the issue is that idle connections are timing out _while in the pool_ then that should fix it.

@shilei9213 can you please confirm that this is what you are experiencing: that idle *pooled* connections are timing out, and it's not that you have opened a session and left it open for a long time.

**Comment by gavinking** [comment]
> (Aside: I notice from the c3p0 documentation that these days there is also a `maxConnectionAge ` property, which honestly Hibernate should also let you set.)

Oh, right, actually you can set this using `hibernate.c3p0. maxConnectionAge`, it appears. Unknown properties with the prefix `hibernate.c3p0` just get passed through to c3p0.

**Comment by gavinking** [comment]
Gawd, that wrong blog post is the first thing that pops up on a Google search for "reconnection Hibernate MySQL". 😭😤

**Comment by gavinking** [comment]
> he goes off on a silly discussion about reconnecting

To be clear, his complaint that Hibernate can't "reconnect" is meaningless. There's no difference at all between "reconnect an expired connection" and "obtain a new connection". They're the same exact thing.

**Comment by shilei9213** [comment]
> > So for Hibernate Reactive, and the Vert.x SQL client, you should set `hibernate.vertx.pool.idle_timeout`.
> > In time, we'll probably want to add additional flexibility here. But if the issue is that idle connections are timing out _while in the pool_ then that should fix it.
> 
> @shilei9213 can you please confirm that this is what you are experiencing: that idle _pooled_ connections are timing out, and it's not that you have opened a session and left it open for a long time.

😄

Thank you.

I think it's good for a connection to be closed if it is idle for a long time.

But our major problem is  the closed connection is always got when we execute sql after that.

I guess vert.x framework could drop this connection and return a new valid connection when we need.

(MySQLPoolImpl)

But i don't known how to do that.

**Comment by gavinking** [comment]
> But our major problem is the closed connection is always got when we execute sql after that.

Well I still don't understand what you're saying here. See there's two reasons you might experience this error:

1. You're holding a single Hibernate session open for a long time: this is Bad and you shouldn't do it.
2. You didn't set `hibernate.vertx.pool.idle_timeout` to be less than MySQL's connection timeout: this is easy to fix, just set it.

But I can't tell which of those cases you're describing. Is it a *pooled* connection that's timing out, or is it a connection belonging to a session that has been held open?

**Comment by BillyYccc** [comment]
The MySQL server will directly close the underlying TCP connection if there is no activity in the connection after `wait_timeout`.

There might be two possibilities for the MySQL pool:
1. the idled connection is in the pool and closed by the server, in this case the pool will automatically evict the closed connection and recreate a new connection later on need.(this should be supported now, if not it must be a bug)
2. the idled connection is borrowed from the pool and managed by the caller(user), after timeout the connection is closed and the pool will evict the connection and recreate a new one later on need but can do nothing stopping you from doing more operations on the closed connection, and if there is some new oepration on the closed connection, you will see the exception as above.

Here are two tests for verifying the above scenes: https://github.com/eclipse-vertx/vertx-sql-client/pull/865

I don't exactly if you directly operate with the session object and do not close it back to pool or how the underlying connection is managed by Quarkus(it seems the Hibernate session is request scoped and closed after executions end?)

**Comment by shilei9213** [comment]
> The MySQL server will directly close the underlying TCP connection if there is no activity in the connection after `wait_timeout`.
> 
> There might be two possibilities for the MySQL pool:
> 
> 1. the idled connection is in the pool and closed by the server, in this case the pool will automatically evict the closed connection and recreate a new connection later on need.(this should be supported now, if not it must be a bug)
> 2. the idled connection is borrowed from the pool and managed by the caller(user), after timeout the connection is closed and the pool will evict the connection and recreate a new one later on need but can do nothing stopping you from doing more operations on the closed connection, and if there is some new oepration on the closed connection, you will see the exception as above.
> 
> Here are two tests for verifying the above scenes: #865
> 
> I don't exactly know if you directly operate with the session object and do not close it back to pool or how the underlying connection is managed by Quarkus(it seems the Hibernate session is request scoped and closed after executions end?)

Thank you for your help!

It should be about the use of vert.x by quarkus. I'll consult the support staff of quarkus.
