### ISSUE TITLE
NullPointerException- JDBC-Client when using preparedQuery with Cubrid DB

### ISSUE THREAD

**Issue by DaveO-Home** [eclipse-vertx/vertx-sql-client#864]
### Version

both 4.0.0 and 4.0.1-SNAPSHOT

### Context

Fails with both non and transaction prepared quires, works with queries without parametes
### Do you have a reproducer?
No

### Error
```
java.lang.NullPointerException
        at cubrid.jdbc.driver.CUBRIDResultSet.getMetaData(CUBRIDResultSet.java:673)
        at io.agroal.pool.wrapper.ResultSetWrapper.getMetaData(ResultSetWrapper.java:460)
        at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:185)
        at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:69)
        at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
        at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
        at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

### Extra

* Fedora33 - JVM 1.8 and Java11
* Query - 
```
pool.rxGetConnection().flatMap(conncubrid ->
          conncubrid.rxBegin().flatMap(tx -> conncubrid.preparedQuery(getUserById())
              .rxExecute(parameters).doOnSuccess(rows -> {
                  Long val[] = { 0L };
                  for(Row row : rows) {
                      val[0] = row.getLong(0);
                  }
                  tx.commit();
                  conncubrid.close();
              }).doOnError(err -> {
                  logger.error(String.format("%sError Retrieving User: %s%s", ColorUtilConstants.RED,
                      err, ColorUtilConstants.RESET));
                  err.printStackTrace();
                  conncubrid.close();
              })
          )).subscribe(rows2 -> {
              System.out.println(rows2.size());
          }, err -> {
              err.printStackTrace();
          });
```

**Comment by vietj** [comment]
can you reopen this issue here https://github.com/vert-x3/vertx-jdbc-client ?
