### ISSUE TITLE
[vertx-mysql-client] MySQL throws exception when run prepared query immediately after creating pool

### ISSUE THREAD

**Issue by YuyuZha0** [eclipse-vertx/vertx-sql-client#870]
```
io.vertx.mysqlclient.MySQLException: Unknown prepared statement handler (1) given to mysqld_stmt_execute
	at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:38)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:57)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:109)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:77)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:66)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**The exception is reproducable, my client version is 4.0.0**

```
  @Singleton
  @Provides
  MySQLPool provideMySQLPool(Vertx vertx, @Named("auth.mysql.uri") String mysqlUri) {
    MySQLConnectOptions mySQLConnectOptions = MySQLConnectOptions.fromUri(mysqlUri);
    mySQLConnectOptions.setCachePreparedStatements(true);
    PoolOptions poolOptions = new PoolOptions().setMaxSize(2);
    return MySQLPool.pool(vertx, mySQLConnectOptions, poolOptions);
  }
```

```
mysqlPool
          .preparedQuery(
              "select app_secret from t_monitor_agent_auth where app_id=? and enable_status=1 limit 1")
          .execute(Tuple.of(appId))
          .map(
              (RowSet<Row> rowSet) -> {
                for (Row row : rowSet) {
                  String appSecret = row.getString(0);
                  if (StringUtils.isNotBlank(appSecret)) {
                    HashFunction hashFunction =
                        Hashing.hmacMd5(appSecret.getBytes(StandardCharsets.UTF_8));
                    return Optional.of(hashFunction);
                  }
                }
                return Optional.<HashFunction>empty();
              })
          .toCompletionStage()
          .toCompletableFuture();
```

**Comment by BillyYccc** [comment]
Hi, there is a same case reported some time ago and it has been fixed. we have a testcase in https://github.com/eclipse-vertx/vertx-sql-client/blob/60fdcd786fbbd7565d5c4e93a9bf905f07b8045f/vertx-mysql-client/src/test/java/io/vertx/mysqlclient/MySQLPoolTest.java#L74-L94

I tried to enable the cache and it also passes, as I don't see any difference with your reproducer can you try to make some changes to break the test?

**Comment by vietj** [comment]
is it fixed in master branch for 4.0.1 @BillyYccc ?

**Comment by BillyYccc** [comment]
I think it was fixed in https://github.com/eclipse-vertx/vertx-sql-client/issues/590 and we had a test, I'm not sure if we got a new bug here.

**Comment by vietj** [comment]
can you double check with the reproducer ?

**Comment by BillyYccc** [comment]
@YuyuZha0 I wonder what the database server and version are you using?

**Comment by BillyYccc** [comment]
Note some MySQL proxies or servers might not support prepared statement.

**Comment by YuyuZha0** [comment]
> Note some MySQL proxies or servers might not support prepared statement.

My mysql version is 5.7, I test it with jdbc and it works fine;, finaly I have to change back to jdbc as a work around.

**Comment by YuyuZha0** [comment]
> @YuyuZha0 I wonder what the database server and version are you using?

The exception is reproducable but not all the time, It depends during the starting up process, once enable cache preparedStatements, if exeption occur first time, then the following query will always fail. I wonder if there is a bug
during the preparedStatement construction.

**Comment by BillyYccc** [comment]
Thanks for the info! I will have another check in the cache implementation.

**Comment by BillyYccc** [comment]
@YuyuZha0 could you set `mySQLConnectOptions#setLogActivity(true)` and show me your logs of network packets if you don't mind? you can mail me if you don't want it public.

**Comment by vietj** [comment]
@YuyuZha0 ping

**Comment by YuyuZha0** [comment]
> @YuyuZha0 ping

OK I'll try it later

**Comment by YuyuZha0** [comment]
> @YuyuZha0 ping

```
2021-01-21 17:20:40.230 [vert.x-eventloop-thread-0] ERROR com.tencent.youshu.handler.AuthHandler - Auth with unknown exception:
io.vertx.mysqlclient.MySQLException: Unknown prepared statement handler (1) given to mysqld_stmt_execute
	at io.vertx.mysqlclient.impl.codec.CommandCodec.handleErrorPacketPayload(CommandCodec.java:131)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandBaseCodec.handleInitPacket(ExtendedQueryCommandBaseCodec.java:38)
	at io.vertx.mysqlclient.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:57)
	at io.vertx.mysqlclient.impl.codec.ExtendedQueryCommandCodec.decodePayload(ExtendedQueryCommandCodec.java:109)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decodePacket(MySQLDecoder.java:77)
	at io.vertx.mysqlclient.impl.codec.MySQLDecoder.decode(MySQLDecoder.java:66)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by BillyYccc** [comment]
please show me the network packet flow instead of the stacktrace, that would help us finding out what happened on the wire, you might use https://vertx.io/docs/vertx-core/java/#logging_network_activity or tools like tcpdump or wireshark.

**Comment by BillyYccc** [comment]
it would also be good to compare with using MySQL jdbc connector with property `useServerPrepStmts=true`.

**Comment by YuyuZha0** [comment]
> please show me the network packet flow instead of the stacktrace, that would help us finding out what happened on the wire, you might use https://vertx.io/docs/vertx-core/java/#logging_network_activity or tools like tcpdump or wireshark.

I've append the detail info in the email

**Comment by vietj** [comment]
what is the status on this @BillyYccc ?

**Comment by BillyYccc** [comment]
I have contacted with the author privately some time ago and I can not find any evidence it's a client bug according to the network packet analysis.

**Comment by vietj** [comment]
closing this one for now as it is not proven it's a client bug.
