### ISSUE TITLE
Sql-Client does not work for prepared statements on oracle database

### ISSUE THREAD

**Issue by ukr15** [eclipse-vertx/vertx-sql-client#901]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

4.0.2

### Context

We tried to migrate from JDBC-Client API to SqlClient API. The following reproducer works fine for Postgres but crashes when configured for usage with Oracle.

stream error java.sql.SQLException: Nicht unterstützte Funktion: getMetaData Feb. 18, 2021 7:03:02 VORM. io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.sql.SQLException: Nicht unterstützte Funktion: getMetaData
	at oracle.jdbc.driver.ArrayDataResultSet.getMetaData(ArrayDataResultSet.java:1080)
	at io.agroal.pool.wrapper.ResultSetWrapper.getMetaData(ResultSetWrapper.java:460)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decodeReturnedKeys(JDBCQueryAction.java:182)
	at io.vertx.jdbcclient.impl.actions.JDBCQueryAction.decode(JDBCQueryAction.java:59)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:69)
	at io.vertx.jdbcclient.impl.actions.JDBCPreparedQuery.execute(JDBCPreparedQuery.java:39)
	at io.vertx.ext.jdbc.impl.JDBCConnectionImpl.lambda$schedule$3(JDBCConnectionImpl.java:217)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:179)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:177)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Do you have a reproducer?

A reproducer is a simple project hosted on GitHub (or another forge supporting git clone operation) that has a build file that can be executed to reproduce the issue.

Reproducers are very helpful for contributors and will likely help them fixing your bug faster.

* Link to github project/gist
https://github.com/ukr15/sql-client-error/blob/main/vertx4JdbcTest.zip
### Steps to reproduce

1. Unpack
2. Configure de.test.Vertx4JdbcTest for oracle 
3. mvn clean install
4.  java -jar target/vertx4-jdbc-test-1.0.0-fat.jar

### Extra
Java 11

**Comment by vietj** [comment]
can you move this issue here https://github.com/vert-x3/vertx-jdbc-client ? thanks
