### ISSUE TITLE
Passing your own promise to a PgPoolImpl's execute will throw exceptions on OpenTracerTracing's sendRequest 

### ISSUE THREAD

**Issue by doctorpangloss** [eclipse-vertx/vertx-sql-client#905]
### Version

4.0.2

### Context

From `vertx-jooq`:
```
Promise<RowSet<Row>> rowPromise = Promise.promise();
delegate.preparedQuery(toPreparedQuery(query)).execute(getBindValues(query),rowPromise);
```
Observe it constructs its own promise. Doesn't matter if it runs in a `context`. `rowPromise.context` will be `null`.

Is it typical to pass your own promise into `execute`? I think this is still a bug.

From `opentracing-tracer`:
```
@Override
  public <R> Span sendRequest(Context context,
                              SpanKind kind,
                              TracingPolicy policy,
                              R request,
                              String operation,
                              BiConsumer<String, String> headers,
                              TagExtractor<R> tagExtractor) {
    if (policy == TracingPolicy.IGNORE) {
      return null;
    }
    Span active = context.getLocal(ACTIVE_SPAN);
```

`context` is null. So it will throw with `NullPointerException`. Why? `context` comes from `promise`, not `Vertx.currentContext()`. Makes sense why.

Full exception stacktrace:

```
ERROR i.v.c.impl.ContextImpl Unhandled exception
java.lang.NullPointerException: null
	at io.vertx.tracing.opentracing.OpenTracingTracer.sendRequest(OpenTracingTracer.java:120)
	at io.vertx.tracing.opentracing.OpenTracingTracer.sendRequest(OpenTracingTracer.java:37)
	at io.vertx.sqlclient.impl.tracing.QueryTracer.sendRequest(QueryTracer.java:86)
	at io.vertx.sqlclient.impl.QueryExecutor.executeExtendedQuery(QueryExecutor.java:141)
	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.execute(SqlClientBase.java:138)
	at io.vertx.sqlclient.impl.SqlClientBase$PreparedQueryImpl.execute(SqlClientBase.java:143)
	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.executeAny(ReactiveClassicGenericQueryExecutor.java:154)
	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.execute(ReactiveClassicGenericQueryExecutor.java:65)
	at io.github.jklingsporn.vertx.jooq.classic.reactivepg.ReactiveClassicGenericQueryExecutor.execute(ReactiveClassicGenericQueryExecutor.java:26)
	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO.insert(AbstractVertxDAO.java:138)
	at io.github.jklingsporn.vertx.jooq.shared.internal.AbstractVertxDAO.insert(AbstractVertxDAO.java:132)
        (user code)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:40)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Extra

Maybe the tracer just retrieves `Vertx.currentContext()`? Or should `Promise.promise()` return a promise with the `Vertx.currentContext()` at time of construction?

**Comment by vietj** [comment]
This is unusual to do that (but allowed).

The promise should be transformed into another promise using `context.promise(promise)` early.

**Comment by vietj** [comment]
I think that you should create your own promise correctly instead of using Promise.promise(), either using vertx.promise() or context.promise()

**Comment by vietj** [comment]
otherwise we are going to add code to check a case that should not happen in practice
