### ISSUE TITLE
Unable insert auto increment key 

### ISSUE THREAD

**Issue by zero88** [eclipse-vertx/vertx-sql-client#910]
### Version

`io.vertx:vertx-pg-client:4.0.0`

### Context

Unable insert auto increment key

```sql
CREATE TABLE books
(
    id    SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL
);

INSERT INTO books (id, title)
VALUES (1, 'The Catcher in the Rye'),
       (2, 'Nine Stories'),
       (3, 'Franny and Zooey'),
       (4, 'The Great Gatsby'),
       (5, 'Tender id the Night'),
       (6, 'Pride and Prejudice'),
       (7, 'Professional ASP.NET 4.5 in C# and VB');
```

```
====================================================================================================
18:44:19.956 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - DEFAULT:             insert into "public"."books" ("title") values (?) returning "public"."books"."id", "public"."books"."title"
18:44:19.957 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - NAMED:               insert into "public"."books" ("title") values (:1) returning "public"."books"."id", "public"."books"."title"
18:44:19.957 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - INLINED:             insert into "public"."books" ("title") values ('abc') returning "public"."books"."id", "public"."books"."title"
18:44:19.958 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - NAMED_OR_INLINED:    insert into "public"."books" ("title") values ('abc') returning "public"."books"."id", "public"."books"."title"
18:44:19.958 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - INDEXED:             insert into "public"."books" ("title") values (?) returning "public"."books"."id", "public"."books"."title"
18:44:19.959 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - FORCE_INDEXED:       insert into "public"."books" ("title") values (?) returning "public"."books"."id", "public"."books"."title"
18:44:19.959 [Test worker] DEBUG io.github.zero88.jooq.vertx.QueryHelper - POSTGRESQL:          insert into "public"."books" ("title") values ($1) returning "public"."books"."id", "public"."books"."title"

{ "message": "duplicate key value violates unique constraint \"books_pkey\"", "severity": "ERROR", "code": "23505", "detail": "Key (id)=(1) already exists.", "file": "nbtinsert.c", "line": "427", "routine": "_bt_check_unique", "schema": "public", "table": "books", "constraint": "books_pkey" }
io.vertx.pgclient.PgException: { "message": "duplicate key value violates unique constraint \"books_pkey\"", "severity": "ERROR", "code": "23505", "detail": "Key (id)=(1) already exists.", "file": "nbtinsert.c", "line": "427", "routine": "_bt_check_unique", "schema": "public", "table": "books", "constraint": "books_pkey" }
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
	at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57)
	at io.vertx.pgclient.impl.codec.ExtendedQueryCommandCodec.handleErrorResponse(ExtendedQueryCommandCodec.java:90)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:236)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:122)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Do you have a reproducer?

* Link to github project/gist

### Extra

Fedora 32, openjdk 8

I think it seems blocker/major issue

**Comment by vietj** [comment]
which versions does it precisely fails with ? this issue mentions 4.0.0, did you try 4.0.2 as well ?

**Comment by zero88** [comment]
Same error with `4.0.2`
Could you tell me how to enable debug log for `sql client`? I want to check/monitor the sql client progress if any issue

**Comment by BillyYccc** [comment]
I wonder why you insert with specifying the `id` while it is a serial data type, have you checked there might be a row containing the conflict id?

**Comment by zero88** [comment]
No, I dont add any `id`
```
insert into "public"."books" ("title") values ($1) returning "public"."books"."id", "public"."books"."title"
```

**Comment by zero88** [comment]
Even try, still no luck
```
insert into "public"."books" ("id", "title") values (default, $1) returning "public"."books"."id", "public"."books"."title"
```

**Comment by zero88** [comment]
Ah, I knew a reason. When setup init data, I added manual id and `postgresql` is not able to cover as normal `sequence`. 
`lastval()` still is 0 after initialized data. 
then I need to correct sequence in init data step.

Closed it due to invalid.
Thanks for your support
