### ISSUE TITLE
PGClient: backlash at the end of text in textArray causes DataTypeCodec to fail

### ISSUE THREAD

**Issue by anandramadurg** [eclipse-vertx/vertx-sql-client#957]
### Questions

PGClient while trying to fetch column value containing text array with backslashes at the end of text causes IndexOutOfBound exception

### Version

v4.00

### Context

Encountered when trying to do get of row from DB using PGClient

### Do you have a reproducer?
No

* Link to github project/gist

### Steps to reproduce

1. Create a column of type
 my_status              | text[]                        |           | not null |

2. populate the column with atleast two text in the array
progress_msg              | {"text1","text2\\"}
3. When trying to get data fails with error (
java.lang.IndexOutOfBoundsException: index: 428, length: -42 (expected: range(0, 463))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1426)
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1433)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1420)
        at io.netty.buffer.AbstractByteBuf.checkDstIndex(AbstractByteBuf.java:1445)
        at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:1051)
        at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:49)
        at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1041)
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1248)
        at io.vertx.pgclient.impl.codec.DataTypeCodec.textDecodeArrayElement(DataTypeCodec.java:1524)
        at io.vertx.pgclient.impl.codec.DataTypeCodec.textDecodeArray(DataTypeCodec.java:1505)
        at io.vertx.pgclient.impl.codec.DataTypeCodec.decodeText(DataTypeCodec.java:517)
        at io.vertx.pgclient.impl.codec.RowResultDecoder.decodeRow(RowResultDecoder.java:47)
        at io.vertx.sqlclient.impl.RowDecoder.handleRow(RowDecoder.java:52)
        at io.vertx.pgclient.impl.codec.PgDecoder.decodeDataRow(PgDecoder.java:188)
        at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:90)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:834)

**Comment by anandramadurg** [comment]
Typo there...
progress_msg | {"text1","text2\"}
should be
my_status | {"text1","text2\"}

**Comment by vietj** [comment]
I figured out, thanks
