### ISSUE TITLE
[Db2] Queries with comments don't work in Db2

### ISSUE THREAD

**Issue by DavideD** [eclipse-vertx/vertx-sql-client#998]
I'm trying to run the following query with comments for Db2:
```
/* insert org.hibernate.reactive.IdentityGeneratorWithColumnTransformerTest$EntityWithIdentity */ select id from NEW TABLE (insert into "Table with default values" (id, name, position) values (default, 'Entity: 0', 2))
```
It causes the following exception:
```
Caused by: io.vertx.db2client.DB2Exception: An error occurred with a DB2 operation. SQLCODE=-518  SQLSTATE=07003
	at io.vertx.db2client.impl.drda.NetSqlca.throwSqlError(NetSqlca.java:206)
	at io.vertx.db2client.impl.drda.NetSqlca.complete(NetSqlca.java:97)
	at io.vertx.db2client.impl.drda.DRDAQueryResponse.parseEXCSQLSTTreply(DRDAQueryResponse.java:550)
	at io.vertx.db2client.impl.drda.DRDAQueryResponse.readExecute(DRDAQueryResponse.java:238)
	at io.vertx.db2client.impl.codec.ExtendedQueryCommandBaseCodec.handleUpdateResult(ExtendedQueryCommandBaseCodec.java:92)
	at io.vertx.db2client.impl.codec.ExtendedQueryCommandCodec.decodeUpdate(ExtendedQueryCommandCodec.java:57)
	at io.vertx.db2client.impl.codec.QueryCommandBaseCodec.decodePayload(QueryCommandBaseCodec.java:71)
	at io.vertx.db2client.impl.codec.DB2Decoder.decodePayload(DB2Decoder.java:79)
```

It works fine without the comments.

Thanks

**Comment by vietj** [comment]
@mswatosh can you have a look at this issue ?

**Comment by mswatosh** [comment]
I was able to recreate this locally (though with different SQLCODE and SQLSTATE). I'll keep looking at it tomorrow.

**Comment by vietj** [comment]
thanks a lot, it could be released in 4.1.1 maybe

**Comment by mswatosh** [comment]
Ok, I think I've identified the issue. We're using `startsWith` to determine if this is a query (starts with SELECT, WITH, or VALUES). Since this starts with a comment, we don't notice that it's a query. So I'll need to modify `isQuery` to ignore a block comment at the beginning.

As a workaround, comments that aren't at the beginning still work. So a block comment or `--` comment after the initial SELECT is fine.

**Comment by vietj** [comment]
thanks

**Comment by vietj** [comment]
thanks for the fix @mswatosh !
